'use client';

import { useState, useCallback, useMemo } from 'react';
import { ToolLayout } from '@/components/ToolLayout';
import {
  Printer,
  Copy,
  FileText,
  RotateCcw,
  Settings2,
  Eye,
  Columns,
  Type,
} from 'lucide-react';
import toast from 'react-hot-toast';

// ── Types ──────────────────────────────────────────────────────────────────

interface PageConfig {
  size: string;
  marginTop: number;
  marginRight: number;
  marginBottom: number;
  marginLeft: number;
  orientation: 'portrait' | 'landscape';
}

interface PrintConfig {
  showBackgrounds: boolean;
  showImages: boolean;
  avoidPageBreakInside: string[];
  pageBreakBefore: string[];
  displayLinks: boolean;
  orphans: number;
  widows: number;
  fontSize: number;
  lineHeight: number;
  hideSelectors: string;
}

// ── Defaults ──────────────────────────────────────────────────────────────

const DEFAULT_PAGE: PageConfig = {
  size: 'A4',
  marginTop: 20,
  marginRight: 20,
  marginBottom: 20,
  marginLeft: 20,
  orientation: 'portrait',
};

const DEFAULT_PRINT: PrintConfig = {
  showBackgrounds: false,
  showImages: true,
  avoidPageBreakInside: ['article', 'section', 'table', 'pre', 'figure'],
  pageBreakBefore: ['h2', '.new-section'],
  displayLinks: true,
  orphans: 3,
  widows: 3,
  fontSize: 12,
  lineHeight: 1.5,
  hideSelectors: 'nav, .no-print, .sidebar, footer, .ad',
};

const PAGE_SIZES: Record<string, { width: number; height: number; label: string }> = {
  A3: { width: 297, height: 420, label: 'A3 (297×420mm)' },
  A4: { width: 210, height: 297, label: 'A4 (210×297mm)' },
  A5: { width: 148, height: 210, label: 'A5 (148×210mm)' },
  Letter: { width: 215.9, height: 279.4, label: 'Letter (8.5×11″)' },
  Legal: { width: 215.9, height: 355.6, label: 'Legal (8.5×14″)' },
  Tabloid: { width: 279.4, height: 431.8, label: 'Tabloid (11×17″)' },
  Executive: { width: 184.15, height: 266.7, label: 'Executive (7.25×10.5″)' },
};

const AVOID_INSIDE_PRESETS = ['article', 'section', 'table', 'pre', 'figure', 'code', 'blockquote', 'li', 'tr', 'img', 'canvas', 'svg'];

const PAGE_BREAK_PRESETS = ['h1', 'h2', 'h3', '.chapter', '.new-section', 'section', 'article', '.page-break'];

// ── CSS Generation ─────────────────────────────────────────────────────────

function generatePrintCSS(page: PageConfig, print: PrintConfig): string {
  const lines: string[] = [];

  // @page rule
  lines.push('/* ===== @page ===== */');
  lines.push('@page {');
  if (PAGE_SIZES[page.size]) {
    const { width, height } = PAGE_SIZES[page.size];
    if (page.orientation === 'landscape') {
      lines.push(`  size: ${height}mm ${width}mm;  /* ${page.size} landscape */`);
    } else {
      lines.push(`  size: ${width}mm ${height}mm;  /* ${page.size} */`);
    }
  } else {
    lines.push(`  size: ${page.size};`);
  }
  lines.push(`  margin: ${page.marginTop}mm ${page.marginRight}mm ${page.marginBottom}mm ${page.marginLeft}mm;`);
  lines.push('');
  lines.push('  @top-right {');
  lines.push('    content: counter(page) " / " counter(pages);');
  lines.push('    font-size: 9pt;');
  lines.push('    color: #666;');
  lines.push('  }');
  lines.push('');
  lines.push('  @top-left {');
  lines.push('    content: string(doctitle);');
  lines.push('    font-size: 9pt;');
  lines.push('    color: #666;');
  lines.push('  }');
  lines.push('');
  lines.push('  @bottom-left {');
  lines.push('    content: "Generated by DevBench";');
  lines.push('    font-size: 8pt;');
  lines.push('    color: #999;');
  lines.push('  }');
  lines.push('}');

  // General print rules
  lines.push('');
  lines.push('/* ===== General Print Rules ===== */');
  lines.push('body {');
  lines.push(`  orphans: ${print.orphans};`);
  lines.push(`  widows: ${print.widows};`);
  if (print.fontSize !== 12) lines.push(`  font-size: ${print.fontSize}pt;`);
  if (print.lineHeight !== 1.5) lines.push(`  line-height: ${print.lineHeight};`);
  lines.push('  color: #000;');
  if (!print.showBackgrounds) lines.push('  background: #fff !important;');
  lines.push('}');

  // Colors & Backgrounds
  lines.push('');
  lines.push('/* ===== Colors & Backgrounds ===== */');
  if (!print.showBackgrounds) {
    lines.push('*, *::before, *::after {');
    lines.push('  background: transparent !important;');
    lines.push('  color: #000 !important;');
    lines.push('  box-shadow: none !important;');
    lines.push('  text-shadow: none !important;');
    lines.push('}');
  } else {
    lines.push('* {');
    lines.push('  print-color-adjust: exact;');
    lines.push('  -webkit-print-color-adjust: exact;');
    lines.push('}');
  }

  // Images
  lines.push('');
  lines.push('/* ===== Images ===== */');
  if (print.showImages) {
    lines.push('img, svg, canvas, video {');
    lines.push('  max-width: 100% !important;');
    lines.push('  page-break-inside: avoid;');
    lines.push('}');
  } else {
    lines.push('img, svg, canvas, video {');
    lines.push('  display: none;');
    lines.push('}');
  }

  // Links
  lines.push('');
  lines.push('/* ===== Links ===== */');
  if (print.displayLinks) {
    lines.push('a[href^="http"]::after {');
    lines.push('  content: " (" attr(href) ")";');
    lines.push('  font-size: 0.8em;');
    lines.push('  font-weight: normal;');
    lines.push('  color: #666;');
    lines.push('  word-break: break-all;');
    lines.push('}');
    lines.push('');
    lines.push('a[href^="javascript:"]::after,');
    lines.push('a[href="#"]::after,');
    lines.push('a[href=""]::after {');
    lines.push('  content: none;');
    lines.push('}');
  }

  // Page breaks
  lines.push('');
  lines.push('/* ===== Page Breaks ===== */');
  if (print.avoidPageBreakInside.length > 0) {
    const sel = print.avoidPageBreakInside.join(',\n  ');
    lines.push(`${sel} {`);
    lines.push('  page-break-inside: avoid;');
    lines.push('  break-inside: avoid;');
    lines.push('}');
  }
  if (print.pageBreakBefore.length > 0) {
    lines.push('');
    const sel = print.pageBreakBefore.join(',\n  ');
    lines.push(`${sel} {`);
    lines.push('  page-break-before: always;');
    lines.push('  break-before: page;');
    lines.push('}');
  }

  // Hide elements
  const hideList = print.hideSelectors.split(',').map(s => s.trim()).filter(s => s.length > 0);
  if (hideList.length > 0) {
    lines.push('');
    lines.push('/* ===== Hidden in Print ===== */');
    lines.push(`${hideList.join(',\n  ')} {`);
    lines.push('  display: none !important;');
    lines.push('}');
  }

  // Misc
  lines.push('');
  lines.push('/* ===== Misc ===== */');
  lines.push('h1, h2, h3, h4, h5, h6 {');
  lines.push('  page-break-after: avoid;');
  lines.push('  break-after: avoid;');
  lines.push('}');
  lines.push('');
  lines.push('abbr[title]::after {');
  lines.push('  content: " (" attr(title) ")";');
  lines.push('}');

  return lines.join('\n');
}

// ── Preview Content ────────────────────────────────────────────────────────

const PREVIEW_HTML = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Print Preview</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:Georgia,'Times New Roman',serif;padding:32px;color:#111;line-height:1.6}
h1{font-size:24px;margin-bottom:4px}h2{font-size:18px;margin-top:24px;margin-bottom:8px;color:#2c3e50}
p{margin-bottom:10px}.subtitle{color:#666;font-size:14px;margin-bottom:20px}
nav{background:#f0f4f8;padding:8px 16px;margin-bottom:16px}nav a{margin-right:16px;color:#3b82f6;text-decoration:none;font-size:13px}
blockquote{border-left:3px solid #3b82f6;padding-left:12px;margin:12px 0;color:#555;font-style:italic}
pre{background:#f7f8fa;border:1px solid #e2e8f0;padding:12px;margin:10px 0;font-size:13px;overflow-x:auto}
code{font-family:'SF Mono',Menlo,monospace;font-size:12px}
figure{margin:12px 0}figcaption{font-size:12px;color:#666;margin-top:4px}
table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border:1px solid #ddd;padding:6px 10px;text-align:left;font-size:13px}th{background:#f0f4f8;font-weight:600}
footer{background:#f0f4f8;padding:12px 16px;margin-top:24px;font-size:12px;color:#666}
img{max-width:100%;height:auto}
</style></head>
<body>
<header class="no-print">
<nav><a href="/">Home</a><a href="/about">About</a></nav>
<h1>CSS Print Stylesheet Generator</h1>
<p class="subtitle">See how your document looks when printed</p>
</header>
<article>
<h2>Introduction</h2>
<p>This is a sample document demonstrating CSS print styles. The navigation bar and footer <strong>will be hidden</strong> when printing. Headings force page breaks, and links show their URLs.</p>
<h2>Typography &amp; Readability</h2>
<p>Print styles prioritize readability. Fonts should be serif or sans-serif at 10-12pt, with generous line-height. Margins account for binding.</p>
<blockquote><p>"Good print CSS is invisible — the reader never notices it, they just enjoy reading."</p></blockquote>
<h2>Images &amp; Media</h2>
<figure>
<img src="https://placehold.co/600x300/e2e8f0/64748b?text=Sample+Image" alt="Sample image" width="600" height="300"/>
<figcaption>Fig. 1 — Images respect max-width in print</figcaption>
</figure>
<p>Images use <code>max-width: 100%</code> so they don't bleed off the page.</p>
<h2>Code &amp; Preformatted Text</h2>
<pre><code>/* Print CSS example */
@media print {
  nav, .no-print { display: none; }
  a[href^="http"]::after { content: " (" attr(href) ")"; }
}</code></pre>
<p>Pre blocks avoid page breaks and look best with light borders and monospace fonts.</p>
<h2>Links &amp; References</h2>
<p>Visit <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@page">MDN @page docs</a> for more. Also see <a href="https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/">Smashing Magazine's guide</a> and the <a href="https://www.w3.org/TR/css-page-3/">W3C spec</a>.</p>
<h2>Tables</h2>
<table>
<thead><tr><th>Property</th><th>Value</th><th>Description</th></tr></thead>
<tbody>
<tr><td>page-break-inside</td><td>avoid</td><td>Prevent splitting inside element</td></tr>
<tr><td>page-break-before</td><td>always</td><td>Force break before element</td></tr>
<tr><td>orphans</td><td>3</td><td>Min lines at page bottom</td></tr>
<tr><td>widows</td><td>3</td><td>Min lines at page top</td></tr>
</tbody>
</table>
</article>
<footer class="no-print"><p>&copy; 2026 DevBench. Hidden when printing.</p></footer>
</body></html>`;

// ── Component ──────────────────────────────────────────────────────────────

export default function CssPrintGeneratorPage() {
  const [page, setPage] = useState<PageConfig>(DEFAULT_PAGE);
  const [print, setPrint] = useState<PrintConfig>(DEFAULT_PRINT);
  const [activeTab, setActiveTab] = useState<'preview' | 'css'>('preview');

  const generatedCSS = useMemo(() => generatePrintCSS(page, print), [page, print]);

  const updatePage = useCallback((partial: Partial<PageConfig>) => {
    setPage(prev => ({ ...prev, ...partial }));
  }, []);

  const updatePrint = useCallback((partial: Partial<PrintConfig>) => {
    setPrint(prev => ({ ...prev, ...partial }));
  }, []);

  const toggleAvoidInside = useCallback((selector: string) => {
    setPrint(prev => {
      const current = prev.avoidPageBreakInside;
      if (current.includes(selector)) {
        return { ...prev, avoidPageBreakInside: current.filter(s => s !== selector) };
      }
      return { ...prev, avoidPageBreakInside: [...current, selector] };
    });
  }, []);

  const toggleBreakBefore = useCallback((selector: string) => {
    setPrint(prev => {
      const current = prev.pageBreakBefore;
      if (current.includes(selector)) {
        return { ...prev, pageBreakBefore: current.filter(s => s !== selector) };
      }
      return { ...prev, pageBreakBefore: [...current, selector] };
    });
  }, []);

  const handleCopyCSS = useCallback(() => {
    navigator.clipboard.writeText(generatedCSS).then(() => {
      toast.success('CSS copied to clipboard!');
    });
  }, [generatedCSS]);

  const handleReset = useCallback(() => {
    setPage(DEFAULT_PAGE);
    setPrint(DEFAULT_PRINT);
    toast.success('Reset to defaults');
  }, []);

  const handleCopyPreview = useCallback(() => {
    const css = generatedCSS;
    const previewCss = css.replace(/@page\s*\{[\s\S]*?\}/g, '').replace(/@top-[^}]*\}\s*/g, '').replace(/@bottom-[^}]*\}\s*/g, '');
    const fullHTML = PREVIEW_HTML.replace('</head>', `<style>\n@media print {\n${css}\n}\n${previewCss}\n</style>\n</head>`);
    navigator.clipboard.writeText(fullHTML).then(() => {
      toast.success('Preview HTML copied!');
    });
  }, [generatedCSS]);

  const previewSrcDoc = useMemo(() => {
    const css = generatedCSS;
    const previewCss = css.replace(/@page\s*\{[\s\S]*?\}/g, '').replace(/@top-[^}]*\}\s*/g, '').replace(/@bottom-[^}]*\}\s*/g, '');
    return PREVIEW_HTML.replace('</head>', `<style>\n@media print {\n${css}\n}\n${previewCss}\n</style>\n</head>`);
  }, [generatedCSS]);

  // ── Render ──────────────────────────────────────────────────────────────

  return (
    <ToolLayout
      title="CSS Print Stylesheet Generator"
      description="Build production-ready @media print stylesheets. Configure @page rules, page breaks, link display, typography, and hidden elements — with live preview and one-click CSS copy."
      controls={
        <div className="flex items-center gap-2 ml-auto">
          <button
            onClick={handleReset}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-slate-300 hover:text-white bg-slate-700/50 hover:bg-slate-700 rounded-md transition-colors"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            Reset
          </button>
        </div>
      }
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* LEFT: Controls */}
        <div className="space-y-5">
          {/* @page Configuration */}
          <div className="p-4 rounded-lg bg-surface-light border border-slate-700/50">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-200 mb-3">
              <Settings2 className="w-4 h-4 text-brand-400" />
              @page Configuration
            </h3>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs text-slate-400 mb-1">Paper Size</label>
                <select
                  value={page.size}
                  onChange={e => updatePage({ size: e.target.value })}
                  className="w-full px-2.5 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none"
                >
                  {Object.entries(PAGE_SIZES).map(([key, val]) => (
                    <option key={key} value={key}>{val.label}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Orientation</label>
                <select
                  value={page.orientation}
                  onChange={e => updatePage({ orientation: e.target.value as 'portrait' | 'landscape' })}
                  className="w-full px-2.5 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none"
                >
                  <option value="portrait">Portrait</option>
                  <option value="landscape">Landscape</option>
                </select>
              </div>
            </div>
            <div className="grid grid-cols-4 gap-2 mt-3">
              {(['marginTop', 'marginRight', 'marginBottom', 'marginLeft'] as const).map((key, idx) => (
                <div key={key}>
                  <label className="block text-xs text-slate-400 mb-1">
                    {['Top', 'Right', 'Bottom', 'Left'][idx]}
                  </label>
                  <input
                    type="number"
                    value={page[key]}
                    onChange={e => updatePage({ [key]: Number(e.target.value) })}
                    min={0} max={50}
                    className="w-full px-2 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none"
                  />
                  <span className="text-[10px] text-slate-500">mm</span>
                </div>
              ))}
            </div>
          </div>

          {/* Typography */}
          <div className="p-4 rounded-lg bg-surface-light border border-slate-700/50">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-200 mb-3">
              <Type className="w-4 h-4 text-brand-400" />
              Typography &amp; Layout
            </h3>
            <div className="grid grid-cols-4 gap-3">
              <div>
                <label className="block text-xs text-slate-400 mb-1">Font Size</label>
                <input type="number" value={print.fontSize} onChange={e => updatePrint({ fontSize: Number(e.target.value) })} min={8} max={20}
                  className="w-full px-2 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none" />
                <span className="text-[10px] text-slate-500">pt</span>
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Line Height</label>
                <input type="number" value={print.lineHeight} onChange={e => updatePrint({ lineHeight: Number(e.target.value) })} min={1} max={3} step={0.1}
                  className="w-full px-2 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none" />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Orphans</label>
                <input type="number" value={print.orphans} onChange={e => updatePrint({ orphans: Number(e.target.value) })} min={0} max={10}
                  className="w-full px-2 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none" />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Widows</label>
                <input type="number" value={print.widows} onChange={e => updatePrint({ widows: Number(e.target.value) })} min={0} max={10}
                  className="w-full px-2 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none" />
              </div>
            </div>
          </div>

          {/* Visibility */}
          <div className="p-4 rounded-lg bg-surface-light border border-slate-700/50">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-200 mb-3">
              <Eye className="w-4 h-4 text-brand-400" />
              Visibility &amp; Media
            </h3>
            <div className="space-y-3">
              <label className="flex items-center justify-between cursor-pointer">
                <span className="text-xs text-slate-300">Print backgrounds &amp; colors</span>
                <button onClick={() => updatePrint({ showBackgrounds: !print.showBackgrounds })}
                  className={`relative w-9 h-5 rounded-full transition-colors ${print.showBackgrounds ? 'bg-brand-500' : 'bg-slate-600'}`}>
                  <span className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform"
                    style={{ left: print.showBackgrounds ? 'calc(100% - 18px)' : '2px' }} />
                </button>
              </label>
              <label className="flex items-center justify-between cursor-pointer">
                <span className="text-xs text-slate-300">Show images</span>
                <button onClick={() => updatePrint({ showImages: !print.showImages })}
                  className={`relative w-9 h-5 rounded-full transition-colors ${print.showImages ? 'bg-brand-500' : 'bg-slate-600'}`}>
                  <span className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform"
                    style={{ left: print.showImages ? 'calc(100% - 18px)' : '2px' }} />
                </button>
              </label>
              <label className="flex items-center justify-between cursor-pointer">
                <span className="text-xs text-slate-300">Show link URLs after text</span>
                <button onClick={() => updatePrint({ displayLinks: !print.displayLinks })}
                  className={`relative w-9 h-5 rounded-full transition-colors ${print.displayLinks ? 'bg-brand-500' : 'bg-slate-600'}`}>
                  <span className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform"
                    style={{ left: print.displayLinks ? 'calc(100% - 18px)' : '2px' }} />
                </button>
              </label>
            </div>
            <div className="mt-3">
              <label className="block text-xs text-slate-400 mb-1">Hide these elements (comma-separated)</label>
              <input type="text" value={print.hideSelectors}
                onChange={e => updatePrint({ hideSelectors: e.target.value })}
                className="w-full px-2.5 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded text-slate-200 focus:border-brand-500 focus:outline-none"
                placeholder="nav, .no-print, .sidebar" />
              <p className="text-[10px] text-slate-500 mt-1">Example: nav, .sidebar, .ad-banner, footer</p>
            </div>
          </div>

          {/* Page Breaks */}
          <div className="p-4 rounded-lg bg-surface-light border border-slate-700/50">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-200 mb-3">
              <Columns className="w-4 h-4 text-brand-400" />
              Page Break Controls
            </h3>
            <div className="mb-3">
              <p className="text-xs text-slate-400 mb-2">Avoid page break inside:</p>
              <div className="flex flex-wrap gap-1.5">
                {AVOID_INSIDE_PRESETS.map(sel => (
                  <button key={sel} onClick={() => toggleAvoidInside(sel)}
                    className={`px-2 py-1 text-[11px] rounded-md transition-colors ${print.avoidPageBreakInside.includes(sel)
                      ? 'bg-brand-500/20 text-brand-300 border border-brand-500/40'
                      : 'bg-slate-700/50 text-slate-400 border border-slate-600/30 hover:bg-slate-700'}`}>
                    {sel}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <p className="text-xs text-slate-400 mb-2">Force page break before:</p>
              <div className="flex flex-wrap gap-1.5">
                {PAGE_BREAK_PRESETS.map(sel => (
                  <button key={sel} onClick={() => toggleBreakBefore(sel)}
                    className={`px-2 py-1 text-[11px] rounded-md transition-colors ${print.pageBreakBefore.includes(sel)
                      ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                      : 'bg-slate-700/50 text-slate-400 border border-slate-600/30 hover:bg-slate-700'}`}>
                    {sel}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT: Preview / Output */}
        <div className="space-y-4">
          {/* Tabs */}
          <div className="flex gap-1 p-1 rounded-lg bg-surface-light border border-slate-700/50">
            <button onClick={() => setActiveTab('preview')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs rounded-md transition-colors ${activeTab === 'preview' ? 'bg-brand-500/20 text-brand-300' : 'text-slate-400 hover:text-slate-200'}`}>
              <Eye className="w-3.5 h-3.5" />Live Preview
            </button>
            <button onClick={() => setActiveTab('css')}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs rounded-md transition-colors ${activeTab === 'css' ? 'bg-brand-500/20 text-brand-300' : 'text-slate-400 hover:text-slate-200'}`}>
              <FileText className="w-3.5 h-3.5" />Generated CSS
            </button>
          </div>

          {/* Preview */}
          {activeTab === 'preview' && (
            <div className="rounded-lg border border-slate-700/50 overflow-hidden bg-white">
              <div className="flex items-center justify-between px-3 py-2 bg-slate-800 border-b border-slate-700/50">
                <span className="text-[11px] text-slate-400 flex items-center gap-1.5">
                  <Printer className="w-3.5 h-3.5" />Print preview with your styles applied
                </span>
                <button onClick={handleCopyPreview}
                  className="flex items-center gap-1 px-2.5 py-1 text-[11px] text-slate-300 hover:text-white bg-slate-700 rounded transition-colors">
                  <Copy className="w-3 h-3" />Copy HTML
                </button>
              </div>
              <div className="relative" style={{ height: '520px' }}>
                <iframe srcDoc={previewSrcDoc}
                  className="w-full h-full border-0" title="Print preview" sandbox="allow-same-origin" />
              </div>
            </div>
          )}

          {/* CSS Output */}
          {activeTab === 'css' && (
            <div className="rounded-lg border border-slate-700/50 overflow-hidden">
              <div className="flex items-center justify-between px-3 py-2 bg-slate-800 border-b border-slate-700/50">
                <div className="flex items-center gap-2">
                  <span className="text-[11px] text-slate-400">@media print</span>
                  <span className="text-[11px] text-brand-400">{generatedCSS.split('\n').length} lines</span>
                </div>
                <button onClick={handleCopyCSS}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-white bg-brand-500 hover:bg-brand-600 rounded transition-colors">
                  <Copy className="w-3.5 h-3.5" />Copy CSS
                </button>
              </div>
              <div className="p-4 bg-slate-900 overflow-auto" style={{ maxHeight: '520px' }}>
                <pre className="text-xs font-mono text-slate-300 whitespace-pre leading-relaxed">
                  <code>{generatedCSS}</code>
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </ToolLayout>
  );
}
