import type { Metadata } from 'next';
import { ToolCard } from '@/components/ToolCard';
import {
  Braces,
  Binary,
  Fingerprint,
  Regex,
  Palette,
  Key,
  Anchor,
  Hash,
  Layers,
  Minimize2,
  Maximize2,
  ArrowUpDown,
  PaintBucket,
  Paintbrush,
  Clock,
  Copy,
  Droplets,
  FileCode,
  Layout,
  CalendarClock,
  Grid3X3,
  QrCode,
  Database,
  ArrowLeftRight,
  ArrowRightLeft,
  Shield,
  Server,
  Globe,
  Link,
  DollarSign,
  Coins,
  AlignLeft,
  ShieldCheck,
  SlidersHorizontal,
  Network,
  Tags,
  BarChart3,
  FileWarning,
  Type,
  FileText,
  Eye,
  MapPin,
  Camera,
  Search,
  Radius,
  Scissors,
  Sparkles,
  TrendingUp,
  Ruler,
  Code2,
  Image,
  Box,
  Container,
  Accessibility,
  Square,
  Parentheses,
  TreePine,
  ScrollText,
  PenTool,
  Pencil,
  Calendar,
  FlaskConical,
  Table2,
  Boxes,
  Keyboard,
  Zap,
  GitBranch,
  GripHorizontal,
  Monitor,
  Smartphone,
  Tablet,
  ListTree,
  HardDrive,
  Play,
  Wifi,
  Sun,
  Focus,
  MousePointer2,
  Folders,
  AlignJustify,
  ListOrdered,
  Package,
  Share2,
  Variable,
  FileSpreadsheet,
  PanelRight,
  FileSearch,
  Music,
  GitGraph,
  Heading,
  Cpu,
  Bell,
  Film,
  Columns,
  Repeat,
  RefreshCw,
  Slash,
  Printer,
  FormInput,
  Clipboard,
  ClipboardPaste,
  Brackets,
  Crosshair,
  Gauge,
  Underline,
  Timer,
  GitCommit,
  Waves,
  Mic,
  Radio,
  FileArchive,
  Cookie,
  Pipette,
  Gamepad2,
  Bookmark,
  AlignCenterVertical,
  SunMoon,
  Users,
  ToggleLeft,
} from 'lucide-react';

export const metadata: Metadata = {
  title: 'All Tools',
  description:
    'Browse all free developer tools: JSON formatter, Base64 encoder/decoder, UUID generator, regex tester, CSS Anchor Playground, and more.',
};

const allTools = [
  {
    title: 'JSON Formatter',
    description: 'Format, minify, and validate JSON with syntax highlighting. Perfect for debugging API responses.',
    href: '/tools/json-formatter',
    icon: Braces,
    tags: ['JSON', 'Formatter'],
  },
  {
    title: 'GraphQL Formatter',
    description: 'Format, minify, and prettify GraphQL queries, mutations, and schemas with syntax highlighting. Supports fragments, variables, and directives — 100% client-side.',
    href: '/tools/graphql-formatter',
    icon: GitGraph,
    tags: ['GraphQL', 'Formatter', 'Query', 'Minifier'],
  },
  {
    title: 'Base64 Encoder/Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text. Fast and client-side only.',
    href: '/tools/base64',
    icon: Binary,
    tags: ['Base64', 'Encoder', 'Decoder'],
  },
  {
    title: 'Bookmarklet Builder',
    description: 'Write JavaScript and instantly convert it into a bookmarklet — drag to your bookmarks bar or copy the URL. 11 presets for common tasks like dark mode, color picking, table sorting, and more.',
    href: '/tools/bookmarklet-builder',
    icon: Bookmark,
    tags: ['Bookmarklet', 'JavaScript', 'Bookmark', 'Generator'],
  },
  {
    title: 'UUID Generator',
    description: 'Generate cryptographically random UUID v4 identifiers. Batch generation supported.',
    href: '/tools/uuid-generator',
    icon: Fingerprint,
    tags: ['UUID', 'Generator', 'Batch'],
  },
  {
    title: 'Box Model Visualizer',
    description: 'Interactively build and visualize the CSS box model — margin, border, padding, and content. Real-time rendering, 6 presets, generated CSS output.',
    href: '/tools/box-model-visualizer',
    icon: Box,
    tags: ['CSS', 'Box Model', 'Layout', 'Visualizer'],
  },
  {
    title: 'Regex Tester',
    description: 'Test regular expressions with real-time match highlighting and capture group analysis.',
    href: '/tools/regex-tester',
    icon: Regex,
    tags: ['Regex', 'Tester', 'Highlighting'],
  },
  {
    title: 'URL Parser & Visualizer',
    description: 'Break down URLs into components — protocol, hostname, path, query params, hash. Edit each part and rebuild the URL in real-time. Color-coded visual breakdown.',
    href: '/tools/url-parser',
    icon: Search,
    tags: ['URL', 'Parser', 'Query Params'],
  },
  {
    title: 'CSS Anchor Positioning Playground',
    description: 'Visually build CSS Anchor Positioning layouts — the new Baseline 2026 API that replaces JavaScript tooltip libraries. 3×3 grid, live preview, instant CSS copy.',
    href: '/tools/css-anchor-positioning-playground',
    icon: Anchor,
    tags: ['CSS', 'Anchor', 'Positioning'],
  },
  {
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL in real-time with live preview and color picker.',
    href: '/tools/color-converter',
    icon: Palette,
    tags: ['Color', 'Converter', 'Picker'],
  },
  {
    title: 'CSS Gradient Builder',
    description: 'Build beautiful CSS gradients visually — linear, radial, and conic. Live preview, presets, and instant copy.',
    href: '/tools/css-gradient-builder',
    icon: PaintBucket,
    tags: ['CSS', 'Gradient', 'Design'],
  },
  {
    title: 'Gradient Text Generator',
    description: 'Build stunning gradient text effects — linear, radial, and conic. Live preview, glow effects, 10 presets, instant CSS copy.',
    href: '/tools/gradient-text-generator',
    icon: Type,
    tags: ['CSS', 'Gradient', 'Text', 'Typography'],
  },
  {
    title: 'JWT Debugger',
    description: 'Decode and inspect JWT tokens. View header, payload, signature, and time claims — all client-side.',
    href: '/tools/jwt-debugger',
    icon: Key,
    tags: ['JWT', 'Debugger', 'Auth'],
  },
  {
    title: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-384 & SHA-512 hashes from text or files. Client-side only.',
    href: '/tools/hash-generator',
    icon: Hash,
    tags: ['Hash', 'SHA', 'MD5', 'Crypto'],
  },
  {
    title: 'Cron Expression Builder',
    description: 'Build and understand cron expressions visually. Human-readable output, presets, and next execution times.',
    href: '/tools/cron-builder',
    icon: Clock,
    tags: ['Cron', 'Scheduler', 'Expression'],
  },
  {
    title: 'Color Palette Generator',
    description: 'Generate color palettes using harmony rules — complementary, analogous, triadic, tetradic, and more. Export as CSS variables or Tailwind config.',
    href: '/tools/color-palette',
    icon: Droplets,
    tags: ['Color', 'Palette', 'Design', 'CSS'],
  },
  {
    title: 'Markdown Previewer',
    description: 'Write Markdown with a live split-pane preview. Formatting toolbar, HTML copy, and .md download — all client-side.',
    href: '/tools/markdown-previewer',
    icon: FileCode,
    tags: ['Markdown', 'Preview', 'Editor'],
  },
  {
    title: 'CSS Flexbox Playground',
    description: 'Visually build and test CSS Flexbox layouts. Adjust container and item properties, see live results, and copy the CSS.',
    href: '/tools/flexbox-playground',
    icon: Layout,
    tags: ['CSS', 'Flexbox', 'Layout', 'Design'],
  },
  {
    title: 'CSS Grid Generator',
    description: 'Visually build CSS Grid layouts with live preview. Adjust columns, rows, gaps, alignment, and presets — copy the generated CSS.',
    href: '/tools/css-grid-generator',
    icon: Grid3X3,
    tags: ['CSS', 'Grid', 'Layout', 'Design'],
  },
  {
    title: 'CSS Toggle Switch Generator',
    description: 'Build pure-CSS toggle switches — iOS, Material, Neumorphic, Minimal. Live interactive preview, full size/color/shadow control, copy-ready HTML + CSS.',
    href: '/tools/css-toggle-generator',
    icon: ToggleLeft,
    tags: ['CSS', 'Toggle', 'Switch', 'UI', 'Generator'],
  },
  {
    title: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data. Customizable colors, error correction, and sizes — 100% client-side.',
    href: '/tools/qr-code-generator',
    icon: QrCode,
    tags: ['QR', 'Barcode', 'Generator'],
  },
  {
    title: 'SQL Formatter',
    description: 'Format, beautify, and minify SQL queries with syntax highlighting. Supports MySQL, PostgreSQL, SQLite and more.',
    href: '/tools/sql-formatter',
    icon: Database,
    tags: ['SQL', 'Formatter', 'Minifier'],
  },
  {
    title: 'Timestamp Converter',
    description: 'Convert between UNIX timestamps and human-readable dates. Seconds or milliseconds, 12 timezones, relative time, ISO 8601 & RFC 2822 formats.',
    href: '/tools/timestamp-converter',
    icon: CalendarClock,
    tags: ['Timestamp', 'Date', 'Converter', 'UNIX'],
  },
  {
    title: 'JSON ↔ CSV Converter',
    description: 'Convert JSON arrays to CSV and back. Table preview, CSV escaping, download — all client-side.',
    href: '/tools/json-csv-converter',
    icon: ArrowRightLeft,
    tags: ['JSON', 'CSV', 'Converter', 'Data'],
  },
  {
    title: 'JSON to TypeScript',
    description: 'Generate TypeScript type definitions from JSON data. Nested objects, arrays, unions, optional fields, interface/type toggle — 100% client-side.',
    href: '/tools/json-ts-converter',
    icon: Code2,
    tags: ['JSON', 'TypeScript', 'Types', 'Code Generation'],
  },
  {
    title: 'HTML to JSX',
    description: 'Convert HTML to valid JSX syntax — class→className, inline styles to JS objects, self-closing void elements, SVG/ARIA attributes, comments. 100% client-side.',
    href: '/tools/html-to-jsx',
    icon: FileCode,
    tags: ['HTML', 'JSX', 'React', 'Converter'],
  },
  {
    title: 'SVG to JSX Converter',
    description: 'Convert SVG markup to JSX for React — camelCase all attributes, self-close void elements, convert style strings to JSX objects, live SVG preview. Supports 50+ SVG attributes. 100% client-side.',
    href: '/tools/svg-to-jsx',
    icon: Brackets,
    tags: ['SVG', 'JSX', 'React', 'Converter', 'Icon'],
  },
  {
    title: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hex in real-time. ASCII/Unicode preview, common reference values — all client-side.',
    href: '/tools/number-base-converter',
    icon: Hash,
    tags: ['Number', 'Base', 'Binary', 'Hex', 'Converter'],
  },
  {
    title: 'Number Format Explorer',
    description: 'Explore JavaScript Intl.NumberFormat interactively — format numbers as currency, percent, units, scientific, or compact notation across any locale with live preview and copyable code.',
    href: '/tools/number-format-explorer',
    icon: Hash,
    tags: ['Number', 'Intl', 'Format', 'Currency', 'Locale'],
  },
  {
    title: 'Password Strength Checker',
    description: 'Check password strength with entropy analysis, crack-time estimates, and a 10-point security checklist — 100% client-side.',
    href: '/tools/password-strength-checker',
    icon: Shield,
    tags: ['Password', 'Security', 'Strength', 'Entropy'],
  },
  {
    title: 'HTTP Status Codes',
    description: 'Complete reference for every HTTP status code. Search by code or name, filter by category (1xx–5xx), and get detailed explanations with MDN links.',
    href: '/tools/http-status-codes',
    icon: Server,
    tags: ['HTTP', 'Status', 'Reference', 'API'],
  },
  {
    title: 'URL Encoder / Decoder',
    description: 'Encode and decode URLs and URI components. Handles special characters, query strings, and international text — all client-side.',
    href: '/tools/url-encoder',
    icon: Link,
    tags: ['URL', 'Encoder', 'Decoder'],
  },
  {
    title: 'Slug Generator',
    description: 'Convert text to clean, URL-friendly slugs. Customize separator, case, max length and strip special characters — with history and one-click copy.',
    href: '/tools/slug-generator',
    icon: Slash,
    tags: ['Slug', 'URL', 'SEO', 'Text'],
  },
  {
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for mockups, designs, and prototypes. Customize paragraphs, sentence count, and classic opening.',
    href: '/tools/lorem-ipsum',
    icon: AlignLeft,
    tags: ['Lorem', 'Text', 'Placeholder'],
  },
  {
    title: 'Unix Permissions Calculator',
    description: 'Visually build chmod permissions with checkboxes. See octal notation, symbolic notation, and chmod command output in real-time.',
    href: '/tools/chmod-calculator',
    icon: ShieldCheck,
    tags: ['chmod', 'Unix', 'Permissions'],
  },
  {
    title: 'Code Minifier',
    description: 'Minify CSS, JavaScript, and HTML — strip comments, whitespace, and shrink your code. 100% client-side with size comparison.',
    href: '/tools/code-minifier',
    icon: Minimize2,
    tags: ['Minifier', 'CSS', 'JavaScript', 'HTML'],
  },
  {
    title: 'Code Screenshot',
    description: 'Beautiful code screenshot generator — syntax highlighting with 6 themes, window chrome, PNG export at 2x resolution. Like Carbon, 100% client-side.',
    href: '/tools/code-screenshot',
    icon: Image,
    tags: ['Screenshot', 'Code', 'Carbon', 'Image'],
  },
  {
    title: 'Unit Converter',
    description: 'Convert between hundreds of units across 11 categories — length, area, volume, mass, temperature, speed, time, data storage, pressure, angle, and frequency. 100% client-side.',
    href: '/tools/unit-converter',
    icon: SlidersHorizontal,
    tags: ['Converter', 'Units', 'Length', 'Mass', 'Data'],
  },
  {
    title: 'Unicode Inspector',
    description: 'Inspect any Unicode character — code point, UTF-8/16 bytes, HTML entities, CSS/JS escapes, URL encoding. Browse arrow, math, Greek, and emoji blocks.',
    href: '/tools/unicode-inspector',
    icon: Type,
    tags: ['Unicode', 'Encoding', 'UTF-8', 'Character', 'Reference'],
  },
  {
    title: 'DNS Lookup',
    description: 'Query DNS records for any domain — A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA, PTR. Uses Cloudflare DNS-over-HTTPS, fully client-side.',
    href: '/tools/dns-lookup',
    icon: Network,
    tags: ['DNS', 'Lookup', 'Network', 'Domain'],
  },
  {
    title: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON instantly. Handles nested objects, arrays, booleans, and nulls — pure client-side with sample data.',
    href: '/tools/yaml-json-converter',
    icon: ArrowUpDown,
    tags: ['YAML', 'JSON', 'Converter', 'Config'],
  },
  {
    title: 'Text Analyzer',
    description: 'Analyze text — word count, character count, reading time, speaking time, keyword density, and more. 100% client-side.',
    href: '/tools/text-analyzer',
    icon: BarChart3,
    tags: ['Text', 'Analysis', 'Writing', 'SEO'],
  },
  {
    title: 'Robots.txt Generator',
    description: 'Build robots.txt files interactively — configure user-agents, allow/disallow rules, crawl delays, and sitemaps. Live preview with syntax highlighting and one-click download.',
    href: '/tools/robots-txt-generator',
    icon: FileWarning,
    tags: ['Robots.txt', 'SEO', 'Crawlers', 'Generator'],
  },
  {
    title: 'Sitemap Generator',
    description: 'Build XML sitemaps for search engines — add URLs, set priority and change frequency, batch-import, drag-to-reorder, and export as sitemap.xml. 100% client-side.',
    href: '/tools/sitemap-generator',
    icon: Globe,
    tags: ['Sitemap', 'SEO', 'XML', 'Generator'],
  },
  {
    title: 'Text Case Converter',
    description: 'Convert text between 15 case styles — camelCase, snake_case, kebab-case, CONSTANT_CASE, and more. Smart word detection handles mixed input formats.',
    href: '/tools/text-case-converter',
    icon: Type,
    tags: ['Text', 'Case', 'Converter', 'Formatter'],
  },
  {
    title: 'HTML Entity Converter',
    description: 'Encode and decode HTML entities — named and numeric. Searchable reference table of 200+ entities for characters, symbols, math, arrows, and more.',
    href: '/tools/html-entity-converter',
    icon: FileText,
    tags: ['HTML', 'Entities', 'Encoder', 'Decoder'],
  },
  {
    title: 'Color Contrast Checker',
    description: 'Check color contrast ratios for WCAG 2.1 compliance. Test any foreground/background combination, see AA/AAA scores, and export reports — all client-side.',
    href: '/tools/color-contrast-checker',
    icon: Eye,
    tags: ['Color', 'Contrast', 'WCAG', 'Accessibility'],
  },
  {
    title: 'IP Lookup',
    description: 'Look up geolocation, ISP, timezone, and network info for any IPv4 or IPv6 address. Auto-detect your own IP, see country flags, and copy any field — powered by ipapi.co.',
    href: '/tools/ip-lookup',
    icon: MapPin,
    tags: ['IP', 'Geolocation', 'Network', 'Lookup'],
  },
  {
    title: 'CSS Filter Playground',
    description: 'Build CSS filter effects visually — blur, brightness, contrast, grayscale, hue-rotate, and more. 12 presets, live image preview, backdrop-filter CSS generation, all client-side.',
    href: '/tools/css-filter-playground',
    icon: Camera,
    tags: ['CSS', 'Filter', 'Design', 'Effects'],
  },
  {
    title: 'CSS Border-Radius Generator',
    description: 'Visually craft border-radius corners with individual control, 10 presets, live preview, and CSS output — uniform or per-corner, all client-side.',
    href: '/tools/border-radius-generator',
    icon: Radius,
    tags: ['CSS', 'Border-Radius', 'Design', 'Generator'],
  },
  {
    title: 'CSS Box-Shadow Generator',
    description: 'Design layered box‑shadows visually — offset, blur, spread, opacity, and inset. 10 presets (Neumorphism, Material, Glow), live preview, one‑click CSS copy — all client‑side.',
    href: '/tools/css-box-shadow-generator',
    icon: Square,
    tags: ['CSS', 'Box-Shadow', 'Design', 'Generator'],
  },
  {
    title: 'CSS Clip-Path Maker',
    description: 'Visually build CSS clip-path shapes — 14 presets (circle, ellipse, polygon stars, arrows, traps), parameter sliders, custom polygon editor, and live preview. Instantly copy CSS.',
    href: '/tools/clip-path-maker',
    icon: Scissors,
    tags: ['CSS', 'Clip-Path', 'Shapes', 'Design'],
  },
  {
    title: 'Text-Shadow Generator',
    description: 'Design layered CSS text-shadows visually — neon glow, retro 3D, emboss, and more. Live preview, 8 presets, instant CSS copy — all client-side.',
    href: '/tools/text-shadow-generator',
    icon: Type,
    tags: ['CSS', 'Text-Shadow', 'Typography', 'Design'],
  },
  {
    title: 'CSS Animation Builder',
    description: 'Design CSS @keyframes animations visually — multiple stops with transform, opacity, and color control. 8 presets, live preview, and full CSS output.',
    href: '/tools/css-animation-builder',
    icon: Sparkles,
    tags: ['CSS', 'Animation', 'Keyframes', 'Design'],
  },
  {
    title: 'CSS Easing Visualizer',
    description: 'Design custom cubic-bezier() easing curves — drag control points on a canvas, 12 presets (bounce, elastic, smooth), live animation preview, and one-click CSS/Tailwind export.',
    href: '/tools/css-easing-visualizer',
    icon: TrendingUp,
    tags: ['CSS', 'Easing', 'Animation', 'cubic-bezier'],
  },
  {
    title: 'CSS Unit Converter',
    description: 'Convert between px, rem, em, vw, vh and 20+ CSS units. Absolute, font-relative, and viewport categories with configurable base font size — all client-side.',
    href: '/tools/css-unit-converter',
    icon: Ruler,
    tags: ['CSS', 'Units', 'Converter', 'px', 'rem'],
  },
  {
    title: 'JSON Schema Generator',
    description: 'Generate JSON Schema (Draft 7 / 2020-12) from JSON data. Nested objects, arrays, required fields, additionalProperties — all client-side.',
    href: '/tools/json-schema-generator',
    icon: FileCode,
    tags: ['JSON Schema', 'API', 'Validation', 'Code Generation'],
  },
  {
    title: 'JSON Schema Validator',
    description: 'Validate JSON data against JSON Schema (Draft 7) — deep validation of nested structures, format validation, error tree view, all composition keywords. 100% client-side.',
    href: '/tools/json-schema-validator',
    icon: ShieldCheck,
    tags: ['JSON Schema', 'Validator', 'API', 'Draft 7'],
  },
  {
    title: 'JSON Schema → Mock Data',
    description: 'Generate realistic mock data from JSON Schema — smart property name hints, format-aware generation (email, uuid, date-time), bulk generation up to 50 items. Perfect for prototyping and testing.',
    href: '/tools/json-schema-mock-generator',
    icon: Code2,
    tags: ['JSON Schema', 'Mock Data', 'Mocking', 'Generation', 'Testing'],
  },
  {
    title: 'Image Compressor',
    description: 'Compress and resize images client-side — JPEG, WebP, PNG. Drag-and-drop, quality slider, size comparison, presets for web/social/thumbnails, instant download.',
    href: '/tools/image-compressor',
    icon: Image,
    tags: ['Image', 'Compressor', 'WebP', 'PNG', 'JPEG'],
  },
  {
    title: 'Image Resizer',
    description: 'Resize images to exact dimensions, scale by percentage, or apply social media presets. Instagram, Twitter, YouTube, favicon sizes — instant download, 100% client-side.',
    href: '/tools/image-resizer',
    icon: Maximize2,
    tags: ['Image', 'Resizer', 'Social Media', 'Dimensions'],
  },
  {
    title: 'Image Format Converter',
    description: 'Convert images between JPEG, PNG, WebP, AVIF, and BMP — all client-side. Convert to multiple formats at once, quality slider, transparency handling, size comparison.',
    href: '/tools/image-format-converter',
    icon: RefreshCw,
    tags: ['Image', 'Converter', 'WebP', 'AVIF', 'PNG', 'JPEG'],
  },
  {
    title: 'Image Comparison Slider',
    description: 'Compare two images with a draggable before/after slider — perfect for design iterations, photo retouching, and visual diffs. Horizontal and vertical modes, custom uploads, keyboard controls.',
    href: '/tools/image-comparison-slider',
    icon: ArrowLeftRight,
    tags: ['Image', 'Comparison', 'Before/After', 'Slider'],
  },
  {
    title: 'Currency Converter',
    description: 'Convert between 50 world currencies with live ECB exchange rates. Searchable dropdowns, swap direction, popular pairs, copy, and daily-updated rates via Frankfurter API.',
    href: '/tools/currency-converter',
    icon: DollarSign,
    tags: ['Currency', 'Exchange', 'Finance', 'Converter'],
  },
  {
    title: 'JSON Diff Checker',
    description: 'Compare two JSON documents structurally — added, removed, and changed keys at any nesting level. Color-coded tree view with expand/collapse. 100% client-side.',
    href: '/tools/json-diff',
    icon: ArrowLeftRight,
    tags: ['JSON', 'Diff', 'Compare', 'API'],
  },
  {
    title: 'JSON Flattener / Unflattener',
    description: 'Flatten nested JSON into dot-notation key-value pairs and unflatten them back. Adjustable separator, depth control, array index handling. Perfect for MongoDB docs, CSV prep, and log analysis — 100% client-side.',
    href: '/tools/json-flattener',
    icon: Layers,
    tags: ['JSON', 'Flatten', 'Unflatten', 'MongoDB', 'CSV'],
  },
  {
    title: 'Container Query Builder',
    description: 'Visually build container size queries — set container-type/inline-size/size, add range conditions, preview at any width, and copy production-ready CSS.',
    href: '/tools/container-query-builder',
    icon: Container,
    tags: ['CSS', 'Container Queries', 'Responsive', '2026'],
  },
  {
    title: 'Box Model Visualizer',
    description: 'Interactively build and visualize the CSS box model — margin, border, padding, and content. Real-time rendering, 6 presets, generated CSS output.',
    href: '/tools/box-model-visualizer',
    icon: Box,
    tags: ['CSS', 'Box Model', 'Layout', 'Visualizer'],
  },
  {
    title: 'CSS Typography Playground',
    description: 'Design type scales with mathematical harmony — 8 scales (Minor Third to Golden Ratio), font picker, weight/line-height/spacing controls, live preview, and production-ready CSS custom properties.',
    href: '/tools/css-typography-playground',
    icon: Type,
    tags: ['CSS', 'Typography', 'Type Scale', 'Design'],
  },
  {
    title: 'Color Blindness Simulator',
    description: 'Upload images and see them through 8 types of color vision deficiency (CVD). Compare side-by-side, test colors, and download simulations. Make your designs accessible to 350M+ people.',
    href: '/tools/color-blindness-simulator',
    icon: Accessibility,
    tags: ['Color Blindness', 'Accessibility', 'CVD', 'Simulation'],
  },
  {
    title: 'Glassmorphism Generator',
    description: 'Design frosted-glass UI panels with live preview. 8 presets (Frosted, Dark, Neon, Mint, Ice), blur/saturation/opacity/radius controls, and instant CSS output with backdrop-filter.',
    href: '/tools/glassmorphism-generator',
    icon: Layers,
    tags: ['CSS', 'Glassmorphism', 'Backdrop Filter', 'Design'],
  },
  {
    title: 'WebSocket Tester',
    description: 'Test WebSocket connections — connect, send messages, and see real-time responses. Echo servers, JSON mode, message log — pure client-side.',
    href: '/tools/websocket-tester',
    icon: Wifi,
    tags: ['WebSocket', 'Tester', 'Real-time'],
  },
  {
    title: 'Wake Lock Playground',
    description: 'Explore the Wake Lock API — prevent screen dimming and sleep. See browser support, event log, and live status.',
    href: '/tools/wake-lock-playground',
    icon: Sun,
    tags: ['Wake Lock', 'Web API', 'Screen'],
  },
  {
    title: 'CSS :has() Selector Playground',
    description: 'Experiment with the CSS :has() relational pseudo-class — now Baseline everywhere. Write HTML, compose :has() selectors, and see live highlights on matching elements. 7 real-world presets, match inspector, and generated CSS output.',
    href: '/tools/css-has-playground',
    icon: Parentheses,
    tags: ['CSS', ':has()', 'Selectors', 'Baseline 2026'],
  },
  {
    title: 'CSS Nesting Playground',
    description: 'Write native CSS nesting and see the expanded browser-ready output — now Baseline across all browsers. 8 presets (cards, buttons, forms, layout), real-time expansion, syntax highlighting, &/@nest/@media/@container support.',
    href: '/tools/css-nesting-playground',
    icon: TreePine,
    tags: ['CSS', 'Nesting', 'Baseline 2026', 'Preprocessor-free'],
  },
  {
    title: 'CSS Scroll-Driven Animations',
    description: 'Build CSS scroll-driven animations visually — the new 2026 Baseline API. 8 presets, live scroll preview, timeline/keyframe editor, and production-ready CSS output. No JavaScript required.',
    href: '/tools/scroll-driven-animations',
    icon: ScrollText,
    tags: ['CSS', 'Scroll-Driven', 'Animation', 'Baseline 2026'],
  },
  {
    title: 'SVG Previewer & Optimizer',
    description: 'Paste SVG code, preview it live, validate for common issues, and optimize — strip whitespace, comments, and redundant attributes to shrink file size. 5 sample SVGs, light/dark preview backgrounds, instant download.',
    href: '/tools/svg-previewer',
    icon: PenTool,
    tags: ['SVG', 'Preview', 'Optimizer', 'Minifier'],
  },
  {
    title: 'SVG to Data URI Converter',
    description: 'Convert SVG markup to optimized data URIs for CSS backgrounds, HTML img tags, JavaScript constants, and Markdown. Supports base64 and URL encoding, minification, charset control, live preview, and multi-format output.',
    href: '/tools/svg-to-data-uri',
    icon: FileCode,
    tags: ['SVG', 'Data URI', 'Encoder', 'Base64', 'Inline'],
  },
  {
    title: 'SVG Path Builder',
    description: 'Visually build and edit SVG path data with a live canvas. Drag anchor points, apply 10 shape templates, customize stroke/fill, and export production-ready SVG — 100% client-side.',
    href: '/tools/svg-path-builder',
    icon: Pencil,
    tags: ['SVG', 'Path', 'Vector', 'Builder'],
  },
  {
    title: 'SVG to PNG Converter',
    description: 'Convert SVG to PNG, WebP, or JPEG at any resolution. Set dimensions, scale for HiDPI, transparent backgrounds, drag-and-drop upload — 100% client-side Canvas API.',
    href: '/tools/svg-to-png',
    icon: Image,
    tags: ['SVG', 'PNG', 'Converter', 'Export', 'Rasterize'],
  },
  {
    title: 'SVG → React Converter',
    description: 'Transform any SVG into a production-ready React component. Auto-converts kebab-case to camelCase, class to className, self-closing tags. Choose TypeScript or JS, named or default export, and add size/color/className props — 100% client-side.',
    href: '/tools/svg-to-react',
    icon: Code2,
    tags: ['SVG', 'React', 'TypeScript', 'JSX', 'Converter'],
  },
  {
    title: 'SVG Wave Generator',
    description: 'Create beautiful layered SVG wave dividers for your website sections. Customize colors, curve types (sine, triangle, square, sawtooth, multi-tone), amplitude, frequency, gradients, and export ready-to-use SVG code — 100% client-side.',
    href: '/tools/svg-wave-generator',
    icon: Waves,
    tags: ['SVG', 'Wave', 'Divider', 'Design', 'Generator'],
  },
  {
    title: 'SVG Chart Generator',
    description: 'Generate beautiful, responsive SVG charts — bar, line, area, pie, donut. Custom data and colors, live preview, copy/download SVG — 100% client-side, zero dependencies.',
    href: '/tools/svg-chart-generator',
    icon: BarChart3,
    tags: ['SVG', 'Chart', 'Data', 'Visualization'],
  },
  {
    title: 'Date Calculator',
    description: 'Calculate date differences with year/month/day breakdowns, add or subtract durations, and count down to events. 100% client‑side.',
    href: '/tools/date-calculator',
    icon: Calendar,
    tags: ['Date', 'Calculator', 'Countdown', 'Diff'],
  },
  {
    title: 'CSS color-mix() Playground',
    description: 'Mix colors natively in CSS across 15 color spaces. Pick two colors, set a mix ratio, and get production-ready color-mix() CSS instantly.',
    href: '/tools/color-mix-playground',
    icon: FlaskConical,
    tags: ['CSS', 'color-mix', 'Color', '2025'],
  },
  {
    title: 'CSS 3D Transform Playground',
    description: 'Build CSS 3D transforms visually — perspective, rotateX/Y/Z, translateZ, backface-visibility, and card flip presets. Live preview, instant CSS copy.',
    href: '/tools/css-3d-transform-playground',
    icon: Boxes,
    tags: ['CSS', '3D', 'Transform', 'Perspective'],
  },
  {
    title: 'JSON to Markdown Table',
    description: 'Convert a JSON array of objects into a formatted Markdown table — paste JSON, get a ready-to-use table for READMEs, docs, and PR descriptions.',
    href: '/tools/json-to-markdown-table',
    icon: Table2,
    tags: ['JSON', 'Markdown', 'Table', 'Converter'],
  },
  {
    title: 'JSON to HTML Table',
    description: 'Convert a JSON array of objects into a clean, styled HTML table — embedded CSS, striped rows, hover effects, responsive wrapper. Instantly copy or download.',
    href: '/tools/json-html-table',
    icon: Table2,
    tags: ['JSON', 'HTML', 'Table', 'Converter'],
  },
  {
    title: 'JSON to HTML Form',
    description: 'Convert JSON objects into accessible, production-ready HTML forms with auto-detected field types — email, password, URL, date, color, select, textarea, checkbox, and more.',
    href: '/tools/json-to-form',
    icon: FormInput,
    tags: ['JSON', 'HTML', 'Form', 'Generator'],
  },

  {
    title: 'JSON to Go Struct',
    description: 'Convert JSON into idiomatic Go struct definitions — nested types, json tags, nullable *pointers, omitempty options, and complete main.go usage code. 100% client-side.',
    href: '/tools/json-to-go',
    icon: FileCode,
    tags: ['JSON', 'Go', 'Golang', 'Struct', 'Code Gen'],
  },
  {
    title: 'JSON to Rust Struct',
    description: 'Convert JSON data into idiomatic Rust struct definitions with serde — derive macros, Option types, snake_case fields, serde rename attributes, and nested structs. 100% client-side.',
    href: '/tools/json-to-rust',
    icon: FileCode,
    tags: ['JSON', 'Rust', 'Serde', 'Struct', 'Code Gen'],
  },
  {
    title: 'JSON to Python Dataclasses',
    description: 'Convert JSON into type-annotated Python dataclass definitions — nested dataclasses, Optional types, List types, snake_case fields, and a from_dict() parsing utility. 100% client-side.',
    href: '/tools/json-to-python',
    icon: FileCode,
    tags: ['JSON', 'Python', 'Dataclass', 'Code Gen'],
  },
  {
    title: 'JSON to Kotlin Data Class',
    description: 'Convert JSON data into idiomatic Kotlin data classes — nested types, @SerialName annotations, nullable types, and support for kotlinx.serialization, Gson, Moshi, and Jackson. 100% client-side.',
    href: '/tools/json-to-kotlin',
    icon: FileCode,
    tags: ['JSON', 'Kotlin', 'Data Class', 'Serialization', 'Code Gen'],
  },
  {
    title: 'JSON → Dart',
    description: 'Convert JSON data into Dart classes with fromJson/toJson — nested types, null safety, json_serializable annotations, camelCase/snake_case field naming, and factory constructors. 100% client-side.',
    href: '/tools/json-to-dart',
    icon: FileCode,
    tags: ['JSON', 'Dart', 'Flutter', 'Class', 'Serialization', 'Code Gen'],
  },
  {
    title: 'JSON → Swift Codable',
    description: 'Convert JSON into idiomatic Swift structs with Codable conformance — nested types, CodingKeys for snake_case mapping, Optional handling, URL detection, and ready-to-use decoder code. 100% client-side.',
    href: '/tools/json-to-swift',
    icon: FileCode,
    tags: ['JSON', 'Swift', 'iOS', 'Codable', 'Code Gen'],
  },
  {
    title: 'HTML Table Generator',
    description: 'Build HTML tables visually — add rows/columns, toggle &lt;th&gt; headers, set per-cell alignment, and export clean HTML + CSS.',
    href: '/tools/html-table-generator',
    icon: Table2,
    tags: ['HTML', 'Table', 'Generator'],
  },
  {
    title: 'Keycode Info',
    description: 'Press any key and see every KeyboardEvent property — key, code, keyCode, modifiers, and location. Debug keyboard shortcuts with live event capture and history.',
    href: '/tools/keycode-info',
    icon: Keyboard,
    tags: ['Keyboard', 'Events', 'Debugging'],
  },
  {
    title: 'Semver Calculator',
    description: 'Validate, compare, and bump semantic versions per the full semver 2.0.0 spec. Parse and visualize major/minor/patch/prerelease/build components with one-click bumps.',
    href: '/tools/semver-calculator',
    icon: GitBranch,
    tags: ['Semver', 'Version', 'Release', 'npm'],
  },
  {
    title: 'CSS Scroll Snap Playground',
    description: 'Visually build CSS scroll-snap layouts — carousels, galleries, onboarding slides. Configure snap-type, alignment, padding, and stop behavior. Live preview, 4 presets, instant CSS copy.',
    href: '/tools/css-scroll-snap-playground',
    icon: GripHorizontal,
    tags: ['CSS', 'Scroll Snap', 'Carousel', 'Layout'],
  },
  {
    title: 'User Agent Parser',
    description: 'Parse any user agent string into its components — browser, OS, rendering engine, device type, and CPU architecture. 15 sample UAs, auto-detect your current browser.',
    href: '/tools/user-agent-parser',
    icon: Monitor,
    tags: ['User Agent', 'Parser', 'Browser', 'Debug'],
  },
  {
    title: 'JSON Tree Viewer',
    description: 'Explore deeply nested JSON with an interactive collapsible tree — search by key/value, copy paths and values, upload JSON files, and see node stats. Pure client-side.',
    href: '/tools/json-tree-viewer',
    icon: ListTree,
    tags: ['JSON', 'Tree', 'Explorer', 'Visualizer'],
  },
  {
    title: 'JavaScript Playground',
    description: 'Write and run JavaScript snippets instantly in your browser with live console output and TypeScript support. 7 presets, error handling, timing, and one-click copy — like a browser REPL.',
    href: '/tools/javascript-playground',
    icon: Play,
    tags: ['JavaScript', 'Playground', 'REPL', 'Run'],
  },
  {
    title: 'Event Loop Visualizer',
    description: 'Step through the JavaScript event loop — see call stack, microtask queue, macrotask queue, and Web APIs in action. 5 interactive scenarios with auto-play to understand async execution order.',
    href: '/tools/event-loop-visualizer',
    icon: Repeat,
    tags: ['JavaScript', 'Event Loop', 'Async', 'Education'],
  },
  {
    title: 'HTML to Markdown',
    description: 'Convert HTML to clean Markdown instantly — headings, lists, tables, code blocks, links, images, blockquotes, and more. 3 presets, live preview, 100% client-side.',
    href: '/tools/html-to-markdown',
    icon: FileCode,
    tags: ['HTML', 'Markdown', 'Converter'],
  },
  {
    title: 'SVG Pattern Generator',
    description: 'Create seamless CSS background patterns from 12 SVG pattern types — dots, grids, hexagons, waves, zigzag, and more. Tweak colors, scale, opacity, and rotation with live preview and instant CSS/SVG output.',
    href: '/tools/svg-pattern-generator',
    icon: Grid3X3,
    tags: ['SVG', 'Pattern', 'Background', 'CSS', 'Design'],
  },
  {
    title: 'CSS Outline Generator',
    description: 'Design accessible focus rings, debug outlines, and decorative borders. Choose width, style, color, and offset — copy CSS and :focus-visible snippets.',
    href: '/tools/css-outline-generator',
    icon: Focus,
    tags: ['CSS', 'Outline', 'Accessibility', 'Focus'],
  },
  {
    title: 'CSS Cursor Playground',
    description: 'Explore all 36 CSS cursor values — hover each card to see the cursor in action, filter by category (General, Links, Selection, Resize, Drag & Drop, Zoom), search, and copy CSS with one click.',
    href: '/tools/css-cursor-playground',
    icon: MousePointer2,
    tags: ['CSS', 'Cursor', 'UX', 'Design'],
  },
  {
    title: 'CSS clamp() Generator',
    description: 'Build fluid responsive values with clamp() — no media queries needed. Set min/max values and viewport range, see the curve, and copy ready-to-use CSS. 8 presets for typography, spacing, and sizing.',
    href: '/tools/clamp-generator',
    icon: SlidersHorizontal,
    tags: ['CSS', 'clamp()', 'Responsive', 'Typography'],
  },
  {
    title: 'Media Query Playground',
    description: 'Test CSS media queries against your live viewport — breakpoints, user preferences, device features. 22 presets, real-time results on resize, and instant CSS output. Pure client-side.',
    href: '/tools/media-query-playground',
    icon: Monitor,
    tags: ['CSS', 'Media Queries', '@media', 'Viewport'],
  },
  {
    title: 'CSS Cascade Layers Playground',
    description: 'Explore CSS @layer visually — organize styles into layers, add CSS rules, and see exactly which layer wins the cascade. Rearrange layers, edit properties, resolve conflicts, and copy production-ready @layer CSS.',
    href: '/tools/css-cascade-layers',
    icon: Layers,
    tags: ['CSS', '@layer', 'Cascade', 'Architecture'],
  },
  {
    title: 'HTMX Reference',
    description: 'Complete searchable reference for every HTMX attribute — core requests, triggers, swap strategies, history, validation, OOB swaps, and more. Copy attributes with one click.',
    href: '/tools/htmx-reference',
    icon: Code2,
    tags: ['HTMX', 'Reference', 'Attributes', 'Cheatsheet'],
  },
  {
    title: 'CSS text-wrap Playground',
    description: 'Experiment with text-wrap: balance, pretty, stable — new Baseline 2026 features for professional typography. Live preview.',
    href: '/tools/css-text-wrap-playground',
    icon: AlignJustify,
    tags: ['CSS', 'text-wrap', 'Typography', 'Baseline 2026'],
  },
  {
    title: 'CSS Tooltip Generator',
    description: 'Design production-ready tooltips visually — position, arrow, colors, animations (fade, slide, scale, bounce), and instant CSS copy. 8 presets, gradient backgrounds, 100% visual.',
    href: '/tools/css-tooltip-generator',
    icon: MousePointer2,
    tags: ['CSS', 'Tooltip', 'Design', 'Animation', 'Generator'],
  },
  {
    title: 'CSS Overflow Playground',
    description: 'Experiment with overflow, text-overflow, word-break, overscroll-behavior, and scroll-behavior in real-time. 8 presets for scrolling, ellipsis, word-breaking, and overscroll containment. Live preview and instant CSS copy.',
    href: '/tools/css-overflow-playground',
    icon: Container,
    tags: ['CSS', 'Overflow', 'Scroll', 'Text', 'Layout'],
  },
  {
    title: 'CSS Offset Path Playground',
    description: 'Visually build motion paths — animate elements along circles, ellipses, sine waves, hearts, stars, and custom SVG paths. Live preview, offset-distance slider, offset-rotate control, and instant CSS output.',
    href: '/tools/css-offset-path-playground',
    icon: TrendingUp,
    tags: ['CSS', 'offset-path', 'Motion', 'Animation', 'SVG'],
  },
  {
    title: 'Browser Storage Explorer',
    description: 'Inspect, edit, import, and export localStorage & sessionStorage. Type detection, search, quota usage bar — the DevTools storage panel, supercharged.',
    href: '/tools/browser-storage-explorer',
    icon: HardDrive,
    tags: ['Storage', 'localStorage', 'sessionStorage', 'Debug'],
  },
  {
    title: 'IndexedDB Explorer',
    description: 'Inspect, browse, and export IndexedDB databases — discover all databases on the origin, explore object stores with schema view (keyPath, indexes, auto-increment), filter/search records, view full record details, delete entries, export as JSON/CSV. Like DevTools Application panel, supercharged.',
    href: '/tools/indexeddb-explorer',
    icon: Database,
    tags: ['IndexedDB', 'Storage', 'Debug', 'Browser API', 'Export'],
  },
  {
    title: 'Notification API Playground',
    description: 'Explore the browser Notification API — test permissions, send custom notifications with 8 presets, configure every option, and review your notification history.',
    href: '/tools/notification-playground',
    icon: Bell,
    tags: ['Browser API', 'Notification', 'Push'],
  },
  {
    title: 'Package.json Generator',
    description: 'Build a valid Node.js package.json interactively — configure name, version, scripts, dependencies, and more. Live preview, one-click copy or download.',
    href: '/tools/package-json-generator',
    icon: Package,
    tags: ['package.json', 'npm', 'Node.js', 'Generator'],
  },
  {
    title: 'Social Card Preview',
    description: 'Preview how your meta tags render on Twitter/X, Facebook, LinkedIn, and Discord. Edit title, description, image, and see exact platform renderings — with generated meta tags ready to copy.',
    href: '/tools/social-card-preview',
    icon: Share2,
    tags: ['Meta', 'Social', 'SEO', 'OG', 'Twitter'],
  },
  {
    title: 'Intersection Observer Playground',
    description: 'Visualize the Intersection Observer API live — configure thresholds, root margins, watch entries fire, see boundingClientRect / intersectionRect data. 5 presets for lazy loading, infinite scroll, and ad viewability.',
    href: '/tools/intersection-observer-playground',
    icon: Eye,
    tags: ['Browser API', 'Intersection Observer', 'Performance', 'Lazy Load'],
  },
  {
    title: 'JWT Debugger',
    description: 'Decode, inspect, and validate JSON Web Tokens — parse header & payload, check claims, view expiry timeline, and detect issues. 3 sample tokens, 100% client-side.',
    href: '/tools/jwt-debugger',
    icon: Key,
    tags: ['JWT', 'Auth', 'Debug', 'Security', 'Claims'],
  },
  {
    title: 'CSS Custom Properties Playground',
    description: 'Define, preview, and manage CSS custom properties (variables) — build theme systems, test color schemes, reorder by drag-and-drop, and export production-ready :root CSS with usage examples.',
    href: '/tools/css-custom-properties',
    icon: Variable,
    tags: ['CSS', 'Custom Properties', 'Variables', 'Themes'],
  },
  {
    title: '@font-face Generator',
    description: 'Build production-ready @font-face declarations — font family, weight, style, display strategy, and fallback source URLs. Copy, download, or embed. 8 presets for common patterns.',
    href: '/tools/font-face-generator',
    icon: FileCode,
    tags: ['CSS', '@font-face', 'Typography', 'Fonts'],
  },
  {
    title: 'Font Palette Playground',
    description: 'Customize COLRv1 color font palettes with @font-palette-values — override color indices, choose base palettes, and see your custom colors render live in the Nabla font. 6 presets, instant CSS + HTML export.',
    href: '/tools/font-palette-playground',
    icon: Palette,
    tags: ['CSS', '@font-palette-values', 'COLRv1', 'Color Fonts'],
  },
  {
    title: 'Variable Fonts Playground',
    description: 'Explore variable fonts in real-time — adjust weight, width, slant, optical size, and more across 7 fonts (Roboto Flex, Inter, Recursive, Fraunces, and more). 8 presets, live preview, and instant CSS output.',
    href: '/tools/variable-fonts-playground',
    icon: Type,
    tags: ['CSS', 'Variable Fonts', 'Typography', 'font-variation-settings'],
  },
  {
    title: 'CSS Named Colors',
    description: 'Explore all 148 CSS named colors — search, filter by family, sort by hue or lightness, and copy hex/RGB/HSL values. Interactive color grid with instant preview.',
    href: '/tools/css-named-colors',
    icon: Palette,
    tags: ['CSS', 'Colors', 'Reference', 'Design'],
  },
  {
    title: 'CSV Viewer & Editor',
    description: 'Paste CSV data and view it as an interactive, editable table — sort by column, filter rows, view column stats (min/max/avg/sum), and export as CSV, TSV, or Markdown. 100% client-side.',
    href: '/tools/csv-viewer',
    icon: FileSpreadsheet,
    tags: ['CSV', 'Table', 'Editor', 'Data', 'Spreadsheet'],
  },
  {
    title: 'CSS Print Stylesheet Generator',
    description: 'Build production-ready @media print stylesheets. Configure @page rules, page breaks, link display, typography, and hidden elements — live preview and one-click CSS copy.',
    href: '/tools/css-print-generator',
    icon: Printer,
    tags: ['CSS', 'Print', '@media', '@page', 'Stylesheet'],
  },
  {
    title: 'CSS Popover API Playground',
    description: 'Build interactive popovers with zero JavaScript — the new Baseline 2026 API. Tooltips, menus, dialogs, drawers, and notifications with just HTML attributes and CSS. 6 presets, live preview, ::backdrop control, and code export.',
    href: '/tools/css-popover-playground',
    icon: PanelRight,
    tags: ['CSS', 'Popover', 'Baseline 2026', 'Tooltip', 'Dialog'],
  },
  {
    title: 'CIDR / Subnet Calculator',
    description: 'Calculate subnet masks, network/broadcast addresses, host ranges, and wildcard masks. Supports CIDR notation (10.0.0.0/8) and dotted-decimal masks. Visual bit bar, 12 presets — 100% client-side.',
    href: '/tools/subnet-calculator',
    icon: Network,
    tags: ['CIDR', 'Subnet', 'IP', 'Network', 'DevOps'],
  },
  {
    title: 'MIME Type Lookup',
    description: 'Search and browse 150+ MIME types by extension or content type. Filter by category (text, image, audio, video, font, model, application). Click any value to copy — 100% client-side.',
    href: '/tools/mime-type-lookup',
    icon: FileSearch,
    tags: ['MIME', 'Content-Type', 'Reference', 'HTTP', 'Headers'],
  },
  {
    title: 'Docker Compose Builder',
    description: 'Visually build docker-compose.yml files — add services, configure ports, volumes, environment variables, restart policies and dependencies. 4 presets (WP+MySQL, Node+PG, Nginx+App, Redis), live YAML preview, instant copy & download.',
    href: '/tools/docker-compose-builder',
    icon: Package,
    tags: ['Docker', 'Compose', 'DevOps', 'YAML', 'Generator'],
  },
  {
    title: 'Web Audio Synthesizer',
    description: 'Play a synthesizer in your browser — sine, square, sawtooth, and triangle waves with ADSR envelope, live waveform visualization, presets, and keyboard input.',
    href: '/tools/audio-synthesizer',
    icon: Music,
    tags: ['Audio', 'Synthesizer', 'Web Audio API', 'Music', 'ADSR'],
  },
  {
    title: 'Audio Recorder',
    description: 'Record audio from your microphone — live waveform, pause/resume, playback with progress, download as WebM. Save multiple recordings with full history — pure client-side.',
    href: '/tools/audio-recorder',
    icon: Mic,
    tags: ['Audio', 'Recorder', 'Microphone', 'MediaRecorder'],
  },
  {
    title: 'Mermaid Live Editor',
    description: 'Create flowcharts, sequence diagrams, and more with Mermaid.js — live preview, 8 sample diagrams, export as SVG/PNG. Diagrams as code, right in your browser.',
    href: '/tools/mermaid-editor',
    icon: GitGraph,
    tags: ['Mermaid', 'Diagram', 'Flowchart', 'Documentation'],
  },
  {
    title: 'CSS @property Playground',
    description: 'Define typed CSS custom properties with the @property at-rule — syntax checking, inheritance, animation. Live preview, 5 presets, generated CSS output.',
    href: '/tools/css-at-property',
    icon: Cpu,
    tags: ['CSS', '@property', 'Custom Properties', 'Animation'],
  },
  {
    title: 'CSS @counter-style Playground',
    description: 'Define custom list counters visually — star ratings, circled numbers, roman numerals, emoji bullets. 8 presets, live <ol> preview, generated CSS — 100% client-side.',
    href: '/tools/css-counter-style-playground',
    icon: ListOrdered,
    tags: ['CSS', '@counter-style', 'Lists', 'Typography'],
  },
  {
    title: 'CSS animation-composition Playground',
    description: 'Visualize how animation-composition (replace | add | accumulate) controls how multiple animations combine. Layer animations, toggle composition per-layer, compare solo vs combined — live preview with generated CSS.',
    href: '/tools/css-animation-composition-playground',
    icon: Layers,
    tags: ['CSS', 'animation-composition', 'Animation', 'Keyframes'],
  },
  {
    title: 'HTTP Headers Reference',
    description: 'Complete searchable reference for 60+ HTTP headers — security, CORS, caching, authentication, proxies, cookies. Filter by category, view examples, copy in one click.',
    href: '/tools/http-headers',
    icon: Heading,
    tags: ['HTTP', 'Headers', 'Reference', 'Security', 'CORS'],
  },
  {
    title: 'Cache-Control Header Builder',
    description: 'Visually construct Cache-Control HTTP headers — toggle directives (max-age, s-maxage, stale-while-revalidate, no-store, immutable), set durations with quick-pick values, apply presets, get usage examples for Nginx/Express/Next.js/Cloudflare/Apache, copy the result.',
    href: '/tools/cache-control-builder',
    icon: Timer,
    tags: ['HTTP', 'Cache-Control', 'Caching', 'Headers', 'Builder'],
  },
  {
    title: 'PWA Manifest Generator',
    description: 'Build a web app manifest.json visually — name, icons, theme colors, display mode, screenshots, shortcuts, and more. Instant JSON output for installable PWAs.',
    href: '/tools/pwa-manifest-generator',
    icon: Monitor,
    tags: ['PWA', 'Manifest', 'Mobile'],
  },
  {
    title: 'CSS accent-color Playground',
    description: 'Style native form controls with one CSS property — checkboxes, radio buttons, range sliders, progress bars, and selects. Live preview, color presets, instant CSS output.',
    href: '/tools/css-accent-color-playground',
    icon: Palette,
    tags: ['CSS', 'accent-color', 'Forms', 'Design'],
  },
  {
    title: '.env File Parser & Validator',
    description: 'Parse, validate, and inspect .env files — detect syntax errors, expand $VAR references, view resolved vs raw values, and export clean environment files.',
    href: '/tools/env-file-validator',
    icon: FileText,
    tags: ['Env', 'Variables', 'Validator', 'DevOps'],
  },
  {
    title: 'CSS :nth-child() Calculator',
    description: 'Visually test and build :nth-child() selectors. Adjust the formula an+b, change item count, see exactly which items match in real time. Supports :nth-last-child, :nth-of-type, and :nth-last-of-type.',
    href: '/tools/nth-child-calculator',
    icon: Hash,
    tags: ['CSS', ':nth-child()', 'Selectors', 'Calculator'],
  },
  {
    title: 'CSS Keyframes Builder',
    description: 'Visually design CSS @keyframes animations — add stops, tweak properties, and get production-ready CSS with live preview.',
    href: '/tools/css-keyframes-builder',
    icon: Film,
    tags: ['CSS', 'Keyframes', 'Animation', 'Builder'],
  },
  {
    title: 'CSS Specificity Calculator',
    description: 'Calculate and visualize CSS selector specificity — parse any selector, see the ID/class/element breakdown, compare two selectors head-to-head, and learn which rule wins. Reference table and 17 presets included.',
    href: '/tools/css-specificity-calculator',
    icon: Layers,
    tags: ['CSS', 'Specificity', 'Selector', 'Calculator'],
  },
  {
    title: 'CSS Multi-Column Playground',
    description: 'Visually build multi-column layouts — newspaper, magazine, dictionary. column-count, column-width, column-gap, column-rule, column-span, column-fill — live preview, 6 presets, instant CSS + Tailwind copy.',
    href: '/tools/css-multicol-playground',
    icon: Columns,
    tags: ['CSS', 'Multi-Column', 'Layout', 'columns'],
  },
  {
    title: 'Git Command Explorer',
    description: 'Browse, search, and copy 45+ essential Git commands — from setup to advanced recovery. Filter by category and difficulty, 100% client-side.',
    href: '/tools/git-command-explorer',
    icon: GitBranch,
    tags: ['Git', 'Commands', 'Reference', 'DevOps'],
  },
  {
    title: 'CSS @starting-style Playground',
    description: 'Design entry animations from display:none with the @starting-style at-rule — 6 presets (dialog, tooltip, drawer, card, notification, slide-in), live preview, and generated CSS + JS.',
    href: '/tools/css-starting-style-playground',
    icon: Sparkles,
    tags: ['CSS', '@starting-style', 'Animation', 'Baseline 2026'],
  },
  {
    title: 'CSS Highlight API Playground',
    description: 'Style arbitrary text ranges with ::highlight() pseudo-elements — no DOM mutation, no reflow. Multiple highlight groups, search-based auto-highlighting, live preview, CSS + JS code generation.',
    href: '/tools/css-highlight-api-playground',
    icon: Paintbrush,
    tags: ['CSS', 'Highlight API', 'Baseline 2026', 'Browser API'],
  },
  {
    title: 'Password Generator',
    description: 'Generate strong, cryptographically random passwords — crypto.getRandomValues() entropy. Full control over length (4–128), character sets (lower, upper, numbers, symbols), ambiguous character exclusion. Strength meter with entropy bits and crack-time estimates, batch generation, show/hide toggle, copy individual or all, and recent history.',
    href: '/tools/password-generator',
    icon: Key,
    tags: ['Password', 'Generator', 'Security', 'Entropy'],
  },
  {
    title: 'Random Data Generator',
    description: 'Generate realistic fake data for testing — names, emails, phone numbers, addresses, companies, credit cards, UUIDs, and more. Select fields, set row count, export as JSON or CSV. 100% client-side.',
    href: '/tools/random-data-generator',
    icon: Database,
    tags: ['Data', 'Generator', 'Testing', 'Mock', 'CSV', 'JSON'],
  },
  {
    title: 'JavaScript Array Methods',
    description: 'Interactive reference for 40+ JavaScript array methods with signatures, examples, and output. Search and filter by category (Creation, Access, Transform, Reorder, Flatten, Join, Iteration). Pure vs mutating badges. 100% client-side.',
    href: '/tools/js-array-methods',
    icon: Braces,
    tags: ['JavaScript', 'Array', 'Methods', 'Reference', 'ES2023', 'ES2024'],
  },
  {
    title: 'Data URL Converter',
    description: 'Encode files and text to data: URLs for inline embedding in HTML/CSS/JS — drag & drop files, view metadata and previews, decode existing data: URLs, download decoded content. 100% client-side with FileReader API.',
    href: '/tools/data-url-converter',
    icon: Link,
    tags: ['Data URL', 'Encoder', 'Decoder', 'Base64', 'Embedding'],
  },
  {
    title: 'Clipboard API Playground',
    description: 'Explore the navigator.clipboard API — write/read text and rich content (images), monitor copy/cut/paste events, check permissions, and export code snippets. All client-side.',
    href: '/tools/clipboard-playground',
    icon: ClipboardPaste,
    tags: ['Clipboard', 'Browser API', 'Permissions', 'Events'],
  },
  {
    title: 'CSS @scope Playground',
    description: 'Visually build CSS @scope rules — define scope roots, set scope limits, write scoped styles, and see live DOM preview. @scope is Baseline 2026 across all browsers — no more BEM naming conventions needed.',
    href: '/tools/scope-playground',
    icon: Crosshair,
    tags: ['CSS', '@scope', 'Scoped Styles', 'Baseline 2026'],
  },
  {
    title: 'CSS Text Decoration Playground',
    description: 'Design text decorations — underline, overline, line-through with solid, double, dotted, dashed, and wavy styles. Control color, thickness, offset, and skip-ink. Live preview, longhand + shorthand CSS.',
    href: '/tools/text-decoration-playground',
    icon: Underline,
    tags: ['CSS', 'Text Decoration', 'Underline', 'Typography'],
  },
  {
    title: 'CSS content-visibility Playground',
    description: 'Explore the performance-boosting content-visibility CSS property — skip rendering off-screen elements, reduce layout cost. Live scroll test with up to 200 cards, real-time visibility tracking, and performance metrics.',
    href: '/tools/content-visibility-playground',
    icon: Gauge,
    tags: ['CSS', 'content-visibility', 'Performance', 'Rendering'],
  },
  {
    title: 'MutationObserver Playground',
    description: 'Observe DOM mutations in real-time — child additions/removals, attribute changes, and character data edits. 5 presets, interactive demo box, configurable observer options — the browser\'s MutationObserver API, live.',
    href: '/tools/mutation-observer-playground',
    icon: Eye,
    tags: ['Browser API', 'MutationObserver', 'Debug', 'DOM'],
  },
  {
    title: 'README Generator',
    description: 'Build a polished README.md with live preview — 11 editable sections, 3 templates (default/minimal/extensive), shields.io badge library with 16 presets + custom badges, copy to clipboard, download as .md file.',
    href: '/tools/readme-generator',
    icon: FileText,
    tags: ['Markdown', 'README', 'Documentation', 'Generator'],
  },
  {
    title: 'StructuredClone Playground',
    description: 'Test JavaScript\'s structuredClone() API — verify what can be deep-cloned, debug DataCloneErrors, explore supported types. 8 samples, reference table of 21 types, 100% client-side.',
    href: '/tools/structured-clone-playground',
    icon: Copy,
    tags: ['Browser API', 'structuredClone', 'Debug', 'Serialization'],
  },
  {
    title: 'Conventional Commit Builder',
    description: 'Build spec-compliant conventional commit messages with a visual editor. Type selector, scopes, breaking changes, footer references, validation, and copy-ready git commands.',
    href: '/tools/conventional-commit-builder',
    icon: GitCommit,
    tags: ['Git', 'Conventional Commits', 'Builder', 'Spec'],
  },
  {
    title: 'HTML Sanitizer',
    description: 'Sanitize user-submitted HTML to prevent XSS attacks. 6 presets (strict, relaxed, markdown-like, email-safe, forum, custom), live code/preview toggle, stripped-element audit log. Uses browser-native DOMParser to strip scripts, event handlers, and unsafe URLs.',
    href: '/tools/html-sanitizer',
    icon: ShieldCheck,
    tags: ['Security', 'HTML', 'XSS', 'Sanitizer'],
  },
  {
    title: 'SRI Hash Generator',
    description: 'Generate Subresource Integrity hashes for CDN scripts and stylesheets — protect against supply chain attacks. Fetch from URL, upload files, or paste content. Get SHA-256/384/512 hashes and ready-to-use HTML tags. 15 popular CDN presets.',
    href: '/tools/sri-hash-generator',
    icon: Shield,
    tags: ['SRI', 'Security', 'Hash', 'Integrity', 'CDN'],
  },
  {
    title: 'CSS @supports Playground',
    description: 'Test CSS feature support against your live browser using the native CSS.supports() API. 50+ preset features across layout, color, typography, interaction, animation & more. Custom property/value tests and full @supports condition support.',
    href: '/tools/css-supports-playground',
    icon: FlaskConical,
    tags: ['CSS', 'Browser', 'Feature Detection', '@supports', 'Compatibility'],
  },
  {
    title: 'SVG to CSS Background',
    description: 'Convert any SVG to a CSS background-image data URI with live preview. URL-encoded or Base64 output, optional color replacement, ready-to-use CSS rules, and size presets for icons.',
    href: '/tools/svg-to-css',
    icon: Image,
    tags: ['SVG', 'CSS', 'Background', 'Data URI', 'Icon'],
  },
  {
    title: 'Responsive Design Tester',
    description: 'Test any URL across multiple device sizes simultaneously — iPhones, iPads, and desktops side-by-side. Landscape/portrait toggle, zoom, custom devices, and horizontal/vertical/grid layouts. Perfect for responsive QA.',
    href: '/tools/responsive-tester',
    icon: Smartphone,
    tags: ['Responsive', 'Testing', 'Devices', 'CSS', 'QA'],
  },
  {
    title: 'ULID Generator',
    description: 'Generate sortable, URL-safe unique identifiers — 26-character, time-based IDs with 80 bits of randomness. Batch generation, inspector, and ULID vs UUID comparison.',
    href: '/tools/ulid-generator',
    icon: Fingerprint,
    tags: ['ULID', 'ID', 'Generator', 'Sortable', 'Crockford'],
  },
  {
    title: 'MIME Type Reference',
    description: 'Complete reference of 70+ MIME types organized by 7 categories — text, image, audio, video, application, font, multipart. Search, filter, and copy Content-Type strings for HTTP headers and API responses.',
    href: '/tools/mime-type-reference',
    icon: FileText,
    tags: ['MIME', 'HTTP', 'Content-Type', 'Reference', 'API'],
  },
  {
    title: 'JSON Sorter',
    description: 'Sort JSON object keys alphabetically — top-level or recursive, ascending or descending. Also sort array values. Clean up messy JSON, make diffs readable, enforce consistent key ordering.',
    href: '/tools/json-sorter',
    icon: ArrowUpDown,
    tags: ['JSON', 'Sort', 'Formatter', 'Keys', 'Diff'],
  },
  {
    title: 'JSON Patch (RFC 6902)',
    description: 'Apply and generate JSON Patch operations — the standard for partial JSON updates used in REST APIs. Supports add, remove, replace, move, copy, and test operations with live diff generation between two documents.',
    href: '/tools/json-patch',
    icon: ArrowLeftRight,
    tags: ['JSON', 'Patch', 'RFC 6902', 'API', 'Diff'],
  },
  {
    title: 'Morse Code Encoder / Decoder',
    description: 'Translate text to Morse code and back in real-time. Live audio playback with speed control (0.5x–2x), visual dot/dash display, clickable character reference, and translation history — 100% client-side Web Audio API.',
    href: '/tools/morse-code',
    icon: Radio,
    tags: ['Morse Code', 'Encoder', 'Decoder', 'Audio', 'Web Audio API'],
  },
  {
    title: 'CSS Pseudo-Elements Playground',
    description: 'Interactively style every CSS pseudo-element — ::before, ::after, ::first-letter, ::selection, ::placeholder, ::marker, ::backdrop, ::file-selector-button, ::spelling-error. Live preview, 8 presets, copy-ready CSS with full selectors.',
    href: '/tools/css-pseudo-elements-playground',
    icon: Layers,
    tags: ['CSS', 'Pseudo-Elements', 'Selectors', '::before', '::after'],
  },
  {
    title: 'CSS Relative Color Syntax Playground',
    description: 'Decompose colors into channels and recompose with math operations — lighten, darken, saturate, shift hues, adjust opacity. CSS Color Level 4 relative color syntax across 7 color spaces.',
    href: '/tools/css-relative-color-playground',
    icon: Pipette,
    tags: ['CSS', 'Color', 'Relative Color Syntax', 'Design', 'OKLCH'],
  },
  {
    title: 'Speech Recognition Playground',
    description: 'Convert speech to text in real-time using the Web Speech API. 20+ languages, continuous mode, live confidence scores — 100% client-side, no servers.',
    href: '/tools/speech-recognition-playground',
    icon: Mic,
    tags: ['Speech', 'Web Speech API', 'Voice', 'Browser API'],
  },
  {
    title: 'Web Share API Playground',
    description: 'Test the Web Share API — share text, links, and files directly from your browser using the native OS share sheet. 3 presets, file attachments, live event log.',
    href: '/tools/web-share-playground',
    icon: Share2,
    tags: ['Web Share', 'Browser API', 'Share', 'Mobile'],
  },

  {
    title: 'Web Crypto Playground',
    description: 'Explore the SubtleCrypto API — hash, HMAC, AES encrypt/decrypt, sign, verify, and generate cryptographic random bytes. 100% client-side.',
    href: '/tools/web-crypto-playground',
    icon: Shield,
    tags: ['Crypto', 'Web Crypto', 'Security', 'AES', 'SHA', 'Browser API'],
  },
  {
    title: 'EXIF Metadata Viewer',
    description: 'Extract and view EXIF metadata from JPEG photos — camera settings, GPS coordinates, timestamps, lens info, and more. 100% client-side binary parsing.',
    href: '/tools/exif-metadata-viewer',
    icon: Camera,
    tags: ['EXIF', 'Metadata', 'Photo', 'GPS', 'Image'],
  },
  {
    title: 'Image Format Converter',
    description: 'Convert images between PNG, JPEG, WebP, AVIF, BMP, and ICO — client-side Canvas rendering with quality control and instant download.',
    href: '/tools/image-format-converter',
    icon: Image,
    tags: ['Image', 'Converter', 'Format', 'WebP', 'AVIF'],
  },
  {
    title: 'srcset & Sizes Generator',
    description: 'Generate responsive image markup — configure width variants, set sizes rules, upload images, and get copy-ready srcset + sizes HTML with a visual preview table.',
    href: '/tools/srcset-generator',
    icon: Image,
    tags: ['Image', 'srcset', 'Responsive', 'HTML', 'Performance'],
  },
  {
    title: 'Compression Playground',
    description: 'Compare GZIP, Deflate, and Deflate Raw compression in real-time. See size savings, compression ratios, hex dumps, and verify round-trip decompression — all client-side via CompressionStream.',
    href: '/tools/compression-playground',
    icon: FileArchive,
    tags: ['Compression', 'GZIP', 'Deflate', 'Performance'],
  },
  {
    title: 'Cookie Editor',
    description: 'Inspect, edit, add, import, and delete browser cookies — full control over name, value, domain, path, max-age, expires, secure flag, and SameSite. Copy all or individual cookies. The document.cookie API, visualized.',
    href: '/tools/cookie-editor',
    icon: Cookie,
    tags: ['Cookies', 'Debug', 'Storage', 'Browser API'],
  },
  {
    title: 'Gamepad API Tester',
    description: 'Test and visualize connected gamepads in real-time — buttons, joysticks, triggers, and vibration. Xbox, PlayStation, and Switch Pro layouts. Built on the Web Gamepad API.',
    href: '/tools/gamepad-api-tester',
    icon: Gamepad2,
    tags: ['Gamepad', 'Browser API', 'Controller', 'Vibration'],
  },
  {
    title: 'Code Minifier',
    description: 'Minify CSS, JavaScript, and HTML — strip comments, collapse whitespace, and reduce file size. Real-time before/after comparison with byte savings. Entirely client-side.',
    href: '/tools/code-minifier',
    icon: Minimize2,
    tags: ['Minifier', 'CSS', 'JavaScript', 'HTML', 'Size Optimization'],
  },
  {
    title: 'CSS color-mix() Playground',
    description: 'Interactively blend colors with CSS color-mix() — 8 color spaces, live preview, copy-ready CSS and Tailwind values. Build dynamic theme effects without preprocessors.',
    href: '/tools/css-color-mix-playground',
    icon: Droplets,
    tags: ['CSS', 'Color', 'color-mix', 'Design', 'OKLCH'],
  },
  {
    title: 'CSS linear() Easing Builder',
    description: 'Design unlimited-stop CSS linear() easing curves — a superset of cubic-bezier(). Create bounce, spring, stepped, and custom easing profiles with a visual curve editor.',
    href: '/tools/css-linear-easing-builder',
    icon: Pipette,
    tags: ['CSS', 'Easing', 'linear()', 'Animation', 'Timing'],
  },
  {
    title: 'CSS text-box Playground',
    description: 'Master text-box-trim and text-box-edge — the Baseline 2026 CSS properties for killing half-leading. Side-by-side comparison, 7 presets, live text properties, copy-ready CSS.',
    href: '/tools/css-text-box-playground',
    icon: AlignCenterVertical,
    tags: ['CSS', 'text-box-trim', 'Typography', 'Baseline 2026'],
  },
  {
    title: 'FormData Explorer',
    description: 'Construct, inspect, and debug FormData objects. Add text and file entries, test all 9 FormData methods (has, get, getAll, set, delete, forEach, entries, keys, values), upload real files, and see live iteration results — 100% client-side.',
    href: '/tools/formdata-explorer',
    icon: FormInput,
    tags: ['FormData', 'Browser API', 'File Upload', 'Debugging', 'Client-Side'],
  },
  {
    title: 'Timezone Converter & World Clock',
    description: 'Convert times between any two timezones, live world clock with day/night indicators, and a meeting planner to find overlap across multiple locations — 100% client-side with Intl.DateTimeFormat.',
    href: '/tools/timezone-converter',
    icon: SunMoon,
    tags: ['Timezone', 'World Clock', 'Meeting', 'Planner', 'UTC'],
  },
  {
    title: 'Fetch Code Generator',
    description: 'Build HTTP requests visually and generate ready-to-run code in JavaScript (fetch), Axios, cURL, Go, Python, and Rust. Send live requests, copy idiomatic code for every ecosystem.',
    href: '/tools/fetch-code-generator',
    icon: Code2,
    tags: ['Fetch', 'HTTP', 'Code Generation', 'cURL', 'API'],
  },
  {
    title: 'CSS env() Playground',
    description: 'Interactively explore CSS env() variables — safe-area-inset, titlebar-area, keyboard-inset. Visual preview on simulated iPhone, foldable, and desktop with real-time CSS output.',
    href: '/tools/css-env-playground',
    icon: Layout,
    tags: ['CSS', 'env()', 'Safe Area', 'Mobile', 'PWA'],
  },
  {
    title: 'HTML Canvas Playground',
    description: 'Write Canvas 2D JavaScript with a live preview — 13 presets across shapes, gradients, animations, text, filters, and transforms. Built-in API reference, export to PNG.',
    href: '/tools/html-canvas-playground',
    icon: PaintBucket,
    tags: ['Canvas', 'JavaScript', 'Graphics', 'Animation', '2D'],
  },
  {
    title: 'CSS Stacking Context Visualizer',
    description: 'Interactive visualizer for CSS stacking contexts — see how opacity, transform, filter, isolation, and 13+ other properties create invisible z-index boundaries. 5 presets with layered visualizations.',
    href: '/tools/css-stacking-context',
    icon: Layers,
    tags: ['CSS', 'z-index', 'Stacking', 'Education'],
  },
  {
    title: 'Roman Numeral Converter',
    description: 'Convert between Arabic numbers and Roman numerals bidirectionally — standard (1–3,999) and extended mode with vinculum for numbers up to 3,999,999. Presets, reference table, instant conversion.',
    href: '/tools/roman-numeral-converter',
    icon: ListOrdered,
    tags: ['Roman Numerals', 'Converter', 'Math', 'Reference'],
  },
  {
    title: 'String Similarity Checker',
    description: 'Compare two strings with Levenshtein, Damerau-Levenshtein, Jaro-Winkler, and a visual character-level diff — perfect for fuzzy matching, spell checking, and dedup.',
    href: '/tools/string-similarity',
    icon: ArrowLeftRight,
    tags: ['String', 'Similarity', 'Diff', 'Levenshtein', 'Fuzzy'],
  },
  {
    title: 'Web Vitals Visualizer',
    description: 'Interactive demos for Core Web Vitals — LCP (Largest Contentful Paint), CLS (Layout Shift), and INP (Interaction Delay). Simulate page loads, layout shifts, and click delays.',
    href: '/tools/web-vitals-visualizer',
    icon: Gauge,
    tags: ['Web Vitals', 'LCP', 'CLS', 'INP', 'Performance', 'Google'],
  },
  {
    title: 'CSS Gap Decorations Playground',
    description: 'Style grid and flex gaps with column-rule and row-rule — new in Chrome 149 (June 2026)! Draw lines, dashes, and dots between items without extra DOM elements.',
    href: '/tools/css-gap-decorations-playground',
    icon: Grid3X3,
    tags: ['CSS', 'Gap', 'Grid', 'Flexbox', 'column-rule', 'row-rule', 'Chrome 149'],
  },
  {
    title: 'CSS Reading Flow Playground',
    description: 'Control tab and screen reader navigation order in flex and grid layouts with reading-flow (CSS Display Level 4). Align accessibility with visual order without changing HTML.',
    href: '/tools/css-reading-flow-playground',
    icon: Eye,
    tags: ['CSS', 'reading-flow', 'Accessibility', 'Tab Order', 'Screen Reader', 'Grid', 'Flexbox'],
  },
];

export default function ToolsPage() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
      <div className="text-center mb-12">
        <h1 className="section-title">All Developer Tools</h1>
        <p className="section-subtitle mt-2">
          Everything runs locally in your browser — no data leaves your machine.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {allTools.map((tool, i) => (
          <ToolCard
            key={tool.href}
            title={tool.title}
            description={tool.description}
            href={tool.href}
            icon={tool.icon}
            tags={tool.tags}
            index={i}
          />
        ))}
      </div>
    </div>
  );
}
