'use client';

import { useState, useCallback, useMemo } from 'react';
import { ToolLayout } from '@/components/ToolLayout';
import { Copy, RotateCcw, Type, Layers, Gauge, Sparkles, Ruler, Info, Check } from 'lucide-react';
import toast from 'react-hot-toast';

// ── Types ──────────────────────────────────────────────────────────────────

interface ScaleRatio {
  name: string;
  ratio: number;
  description: string;
}

interface TypeStep {
  label: string;
  tag: string;
  size: number;
  lineHeight: number;
  fontWeight: string;
  cssClass: string;
}

// ── Scale ratios ───────────────────────────────────────────────────────────

const RATIOS: ScaleRatio[] = [
  { name: 'Minor Second', ratio: 1.067, description: 'Subtle, almost imperceptible — good for dense UIs' },
  { name: 'Major Second', ratio: 1.125, description: 'Gentle progression — clean and minimal' },
  { name: 'Minor Third', ratio: 1.2, description: 'Classic 12px→14px→16px feel — great for body text' },
  { name: 'Major Third', ratio: 1.25, description: 'Balanced and harmonious — common in blogs' },
  { name: 'Perfect Fourth', ratio: 1.333, description: 'Classic typographic scale — print-inspired' },
  { name: 'Augmented Fourth', ratio: 1.414, description: '√2 ratio — mathematical elegance' },
  { name: 'Perfect Fifth', ratio: 1.5, description: 'Bold, dramatic contrast — strong hierarchy' },
  { name: 'Golden Ratio', ratio: 1.618, description: 'Φ — nature\'s most beautiful proportion' },
];

const SCALE_LABELS = [
  { label: 'h1', tag: 'Heading 1', cssClass: 'Heading 1', fontWeight: '700' },
  { label: 'h2', tag: 'Heading 2', cssClass: 'Heading 2', fontWeight: '600' },
  { label: 'h3', tag: 'Heading 3', cssClass: 'Heading 3', fontWeight: '600' },
  { label: 'h4', tag: 'Heading 4', cssClass: 'Heading 4', fontWeight: '600' },
  { label: 'h5', tag: 'Heading 5', cssClass: 'Heading 5', fontWeight: '600' },
  { label: 'body', tag: 'Body / Paragraph', cssClass: 'Body', fontWeight: '400' },
  { label: 'small', tag: 'Small / Caption', cssClass: 'Small / Caption', fontWeight: '400' },
];

// ── Defaults ───────────────────────────────────────────────────────────────

const DEFAULT_BASE = 16;
const DEFAULT_RATIO_INDEX = 4; // Perfect Fourth

export default function TypographyScaleGenerator() {
  const [baseSize, setBaseSize] = useState(DEFAULT_BASE);
  const [ratioIndex, setRatioIndex] = useState(DEFAULT_RATIO_INDEX);
  const [unit, setUnit] = useState<'px' | 'rem'>('rem');
  const [useFluid, setUseFluid] = useState(false);
  const [fluidMinVp, setFluidMinVp] = useState(360);
  const [fluidMaxVp, setFluidMaxVp] = useState(1440);
  const [copySuccess, setCopySuccess] = useState(false);

  const ratio = RATIOS[ratioIndex];

  // ── Compute scale ────────────────────────────────────────────────────────

  const steps = useMemo((): TypeStep[] => {
    const basePx = baseSize;
    // h1 is ratio^6 * base, h2 is ratio^5 * base, ..., body is ratio^1 * base (one step above base), small is base
    return SCALE_LABELS.map((item, i) => {
      const exponent = SCALE_LABELS.length - 1 - i;
      const sizePx = basePx * Math.pow(ratio.ratio, exponent);
      const size = unit === 'rem' ? sizePx / 16 : sizePx;
      const lineHeight = sizePx > 24 ? 1.1 : sizePx > 18 ? 1.25 : sizePx > 14 ? 1.5 : 1.6;
      return {
        ...item,
        size: Math.round(size * 100) / 100,
        lineHeight: Math.round(lineHeight * 100) / 100,
        fontWeight: item.fontWeight,
      };
    });
  }, [baseSize, ratio.ratio, unit]);

  // ── Generate fluid clamp ─────────────────────────────────────────────────

  const fluidClamps = useMemo((): string[] => {
    if (!useFluid) return [];
    return steps.map((step, i) => {
      const exponent = SCALE_LABELS.length - 1 - i;
      const minPx = baseSize * 0.75 * Math.pow(ratio.ratio, exponent);
      const maxPx = baseSize * Math.pow(ratio.ratio, exponent);
      const minRem = minPx / 16;
      const maxRem = maxPx / 16;
      const slope = (maxRem - minRem) / (fluidMaxVp - fluidMinVp) * 100;
      const intercept = minRem - (slope * fluidMinVp) / 100;
      return `clamp(${minRem.toFixed(2)}rem, ${intercept.toFixed(2)}rem + ${slope.toFixed(2)}vw, ${maxRem.toFixed(2)}rem)`;
    });
  }, [useFluid, steps, baseSize, ratio.ratio, fluidMinVp, fluidMaxVp]);

  // ── Copy CSS ─────────────────────────────────────────────────────────────

  const generateCSS = useCallback((): string => {
    const lines: string[] = ['/* Typography Scale — Generated by DevBench */', '/* Ratio: ' + ratio.name + ' (' + ratio.ratio + ') | Base: ' + baseSize + 'px */', ''];
    if (useFluid) {
      lines.push('/* Fluid type scale using clamp() */');
      steps.forEach((step, i) => {
        lines.push(`--text-${step.label}: ${fluidClamps[i]};`);
      });
    } else {
      lines.push(':root {');
      steps.forEach((step) => {
        const value = unit === 'rem' ? (step.size).toFixed(2) + 'rem' : Math.round(step.size) + 'px';
        lines.push(`  --text-${step.label}: ${value};`);
      });
      lines.push('}');
    }
    lines.push('');
    steps.forEach((step) => {
      const value = unit === 'rem' ? (step.size).toFixed(2) + 'rem' : Math.round(step.size) + 'px';
      const lh = step.lineHeight;
      lines.push(`${step.label} { font-size: var(--text-${step.label}, ${value}); line-height: ${lh}; font-weight: ${step.fontWeight}; }`);
    });
    return lines.join('\n');
  }, [steps, unit, ratio, baseSize, useFluid, fluidClamps]);

  const copyCSS = useCallback(() => {
    navigator.clipboard.writeText(generateCSS());
    setCopySuccess(true);
    toast.success('CSS copied! Paste into your stylesheet.');
    setTimeout(() => setCopySuccess(false), 2000);
  }, [generateCSS]);

  const reset = useCallback(() => {
    setBaseSize(DEFAULT_BASE);
    setRatioIndex(DEFAULT_RATIO_INDEX);
    setUnit('rem');
    setUseFluid(false);
    setFluidMinVp(360);
    setFluidMaxVp(1440);
  }, []);

  // ── Scale preview colors ─────────────────────────────────────────────────

  const previewColors = ['#f97316', '#ec4899', '#a855f7', '#6366f1', '#3b82f6', '#10b981', '#64748b'];

  return (
    <ToolLayout
      title="Typography Scale Generator"
      description="Build harmonious type scales with classic musical & mathematical ratios. Live visual preview, fluid clamp() output, and ready-to-use CSS."
      controls={
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={copyCSS}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-brand-600 hover:bg-brand-500 text-white rounded-lg text-sm font-medium transition-colors"
          >
            {copySuccess ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copySuccess ? 'Copied!' : 'Copy CSS'}
          </button>
          <button
            onClick={reset}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-surface-light hover:bg-slate-700 text-slate-300 rounded-lg text-sm transition-colors"
          >
            <RotateCcw className="w-4 h-4" />
            Reset
          </button>
        </div>
      }
    >
      {/* ── Controls ──────────────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {/* Base size */}
        <div className="p-4 rounded-xl bg-surface-light border border-slate-700/50">
          <label className="flex items-center gap-2 text-xs font-medium text-slate-400 uppercase tracking-wider mb-3">
            <Type className="w-3.5 h-3.5" /> Base Size
          </label>
          <div className="flex items-center gap-3">
            <input
              type="range"
              min={12}
              max={24}
              step={1}
              value={baseSize}
              onChange={(e) => setBaseSize(Number(e.target.value))}
              className="flex-1 h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-brand-500"
            />
            <span className="text-sm font-mono text-white min-w-[3rem] text-right">{baseSize}px</span>
          </div>
        </div>

        {/* Ratio selector */}
        <div className="p-4 rounded-xl bg-surface-light border border-slate-700/50">
          <label className="flex items-center gap-2 text-xs font-medium text-slate-400 uppercase tracking-wider mb-3">
            <Ruler className="w-3.5 h-3.5" /> Scale Ratio
          </label>
          <select
            value={ratioIndex}
            onChange={(e) => setRatioIndex(Number(e.target.value))}
            className="w-full bg-slate-800 border border-slate-600 text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-brand-500"
          >
            {RATIOS.map((r, i) => (
              <option key={r.name} value={i}>
                {r.name} ({r.ratio})
              </option>
            ))}
          </select>
        </div>

        {/* Unit */}
        <div className="p-4 rounded-xl bg-surface-light border border-slate-700/50">
          <label className="flex items-center gap-2 text-xs font-medium text-slate-400 uppercase tracking-wider mb-3">
            <Gauge className="w-3.5 h-3.5" /> Output Unit
          </label>
          <div className="flex gap-2">
            {(['rem', 'px'] as const).map((u) => (
              <button
                key={u}
                onClick={() => setUnit(u)}
                className={`flex-1 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                  unit === u
                    ? 'bg-brand-600 text-white'
                    : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                {u}
              </button>
            ))}
          </div>
        </div>

        {/* Fluid toggle */}
        <div className="p-4 rounded-xl bg-surface-light border border-slate-700/50">
          <label className="flex items-center gap-2 text-xs font-medium text-slate-400 uppercase tracking-wider mb-3">
            <Sparkles className="w-3.5 h-3.5" /> Fluid Scale
          </label>
          <button
            onClick={() => setUseFluid(!useFluid)}
            className={`w-full px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
              useFluid
                ? 'bg-brand-600 text-white'
                : 'bg-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            {useFluid ? 'Fluid (clamp) ✓' : 'Fixed'}
          </button>
        </div>
      </div>

      {/* Fluid viewport controls */}
      {useFluid && (
        <div className="flex items-center gap-4 mb-8 p-4 rounded-xl bg-surface-light border border-slate-700/50">
          <span className="text-sm text-slate-400">Viewport:</span>
          <label className="flex items-center gap-2 text-sm text-slate-300">
            Min{' '}
            <input
              type="number"
              value={fluidMinVp}
              onChange={(e) => setFluidMinVp(Number(e.target.value))}
              className="w-20 bg-slate-800 border border-slate-600 text-white rounded-lg px-2 py-1 text-sm text-center"
            />
            px
          </label>
          <label className="flex items-center gap-2 text-sm text-slate-300">
            Max{' '}
            <input
              type="number"
              value={fluidMaxVp}
              onChange={(e) => setFluidMaxVp(Number(e.target.value))}
              className="w-20 bg-slate-800 border border-slate-600 text-white rounded-lg px-2 py-1 text-sm text-center"
            />
            px
          </label>
          <span className="text-xs text-slate-500 ml-auto">{ratio.name} Ratio (×{ratio.ratio})</span>
        </div>
      )}

      {/* ── Visual Scale Preview ──────────────────────────────────────────── */}
      <div className="mb-8">
        <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
          <Layers className="w-4 h-4" /> Visual Scale Preview
        </h2>
        <div className="p-6 rounded-xl bg-surface-light border border-slate-700/50 overflow-x-auto">
          {/* Staircase visualization */}
          <div className="flex flex-col gap-1 mb-8">
            {steps.map((step, i) => (
              <div
                key={step.label}
                className="flex items-center gap-4 py-2 px-3 rounded-lg hover:bg-slate-800/50 transition-colors group"
              >
                {/* Color bar */}
                <div
                  className="shrink-0 rounded transition-all"
                  style={{
                    width: `${Math.max(8, step.size * 1.5)}px`,
                    height: `${Math.max(4, step.size / 4)}px`,
                    backgroundColor: previewColors[i],
                  }}
                />
                {/* Label */}
                <span className="text-xs font-mono text-slate-500 w-8 shrink-0">{step.label}</span>
                {/* Size value */}
                <span className="text-sm font-mono text-brand-400 w-24 shrink-0">
                  {unit === 'rem' ? step.size.toFixed(2) + 'rem' : Math.round(step.size) + 'px'}
                </span>
                {/* Fluid value if enabled */}
                {useFluid && (
                  <span className="text-xs font-mono text-slate-500 truncate hidden lg:block">
                    {fluidClamps[i]}
                  </span>
                )}
                {/* Description */}
                <span className="text-xs text-slate-500 hidden md:block">{step.tag}</span>
              </div>
            ))}
          </div>

          {/* Live type preview */}
          <div className="space-y-4 border-t border-slate-700/50 pt-6">
            {steps.map((step, i) => {
              const Tag = step.label === 'body' ? 'p' : step.label === 'small' ? 'small' : (`h${i + 1}` as keyof JSX.IntrinsicElements);
              const displaySize = unit === 'rem' ? step.size + 'rem' : Math.round(step.size) + 'px';
              return (
                <div key={step.label} className="group">
                  <Tag
                    style={{
                      fontSize: displaySize,
                      lineHeight: step.lineHeight,
                      fontWeight: step.fontWeight as any,
                    }}
                    className="text-white transition-all"
                  >
                    {step.label === 'body'
                      ? 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump!'
                      : step.label === 'small'
                      ? 'Small print / captions / footnotes / metadata — used for secondary information and disclaimers.'
                      : `The Five Boxing Wizards Jump Quickly`}
                  </Tag>
                  <span className="text-xs text-slate-600 opacity-0 group-hover:opacity-100 transition-opacity">
                    {step.label} — {displaySize} / line-height: {step.lineHeight}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* ── Ratio Info ────────────────────────────────────────────────────── */}
      <div className="mb-8 p-4 rounded-xl bg-surface-light border border-slate-700/50">
        <div className="flex items-start gap-3">
          <Info className="w-4 h-4 text-brand-400 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm text-white font-medium mb-1">{ratio.name} Scale (×{ratio.ratio})</p>
            <p className="text-xs text-slate-400">{ratio.description}</p>
            <p className="text-xs text-slate-500 mt-1">
              Base: {baseSize}px — Each heading is {ratio.ratio}× larger than the previous. The classic type scale dates back to 16th-century typographers who used musical intervals as proportions.
            </p>
          </div>
        </div>
      </div>

      {/* ── CSS Output ────────────────────────────────────────────────────── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
            <Copy className="w-4 h-4" /> {useFluid ? 'Fluid CSS (clamp)' : 'Generated CSS'}
          </h2>
        </div>
        <div className="relative">
          <pre className="bg-slate-900 border border-slate-700 rounded-xl p-5 overflow-x-auto text-sm font-mono text-slate-300 leading-relaxed">
            <code>{generateCSS()}</code>
          </pre>
        </div>
      </div>
    </ToolLayout>
  );
}
